### ISSUE TITLE
Item Spawns

### ISSUE THREAD

**Issue by lonewolfss** [Arkensor/DayZCommunityOfflineMode#100]
hi prob the wrong place to ask but how do i add loot spawns into placed buildings via tha map editor. i know i can add items to spawn but that would spawn the same items all the time

**Comment by S4MT3K** [comment]
I Don’t get your question right :/
So you just want to make your building lootable? With random loot, generated by the server?

**Comment by lonewolfss** [comment]
yes thats correct

**Comment by lonewolfss** [comment]
i dont want to have a modded server files i want to keep it vanilla. i know there is a way to add loot spawns in to placed building via the game files but unsure how to atm

**Comment by S4MT3K** [comment]
Dont add them in the Editor. Add it with the function of DaOnes Mod. Activate the proxy export and copy the given file named Mapgrouppos.xml in your db folder in "export" into your mpmissions folder. Replace the existing old one with the generated new one. after that wipe your server (erasing database) and then it should spawn random generated loot depending on what building it is.

If you want to spawn military loot in urban areas let me know. but i would recommened to let the spawnareas like what it was. youll destroy your DayZ experience... Believe me!
