### ISSUE TITLE
Where are the walls and fences?

### ISSUE THREAD

**Issue by robotstar78** [Arkensor/DayZCommunityOfflineMode#102]
Hey all. This mod is just brilliant :)

Any idea where the walls and fences are? I can see fence gates and wall gates, but I really want to add some proper walls and fences to my world. Can't see them in the buildings list

**Comment by S4MT3K** [comment]
Subscribe to builder items mod on workshop. Copy it out of worshop folder and paste it into com Folder. give it a name and edit the batch file. Add -mod=@whateveryounamedit

Feel free to hug me if worked ;)

**Comment by lonewolfss** [comment]
dose that mean you have to have a modded server @S4MT3K ? :(

**Comment by robotstar78** [comment]
Hugs are on their way to you S4MT3K <3

**Comment by S4MT3K** [comment]
@lonewolfss 
Yes. When buildings added, they has to be implemented via a function. 
And the structures has to be in the server AND the client. The user just easyly can subscribe the workshop item. Only you as an server admin have to drag it to the right place.
You also have to set the start parameter to -mod=@modname

If the user has to so it aswell is out of my scope, but i would suggest it anyway.

**Comment by lonewolfss** [comment]
ok  @S4MT3K im just struggling on adding the loot spawns in the building that i have placed
