### ISSUE TITLE
[Feedback] Future features and tweaks

### ISSUE THREAD

**Issue by Cellander** [Arkensor/DayZCommunityOfflineMode#103]
First of all thank you for this mod! Thanks to you [DAYZ - The Way Out](https://youtu.be/WAqpdS7FwtE) was possible. Great work to all of you, I hope COM will have a long future!

I want to do what I can to contribute to the improvement of this mod by writing down some feedback (Some of the entries may already be planned and I don't know if all of it is possible):

**Object Editor**
- Ability or fix(?) scroll (change value) a marked item on the XYZ-axis. Yaw, Pitch, Roll works fine but XYZ just pops the value to 0,05 or -0,05.

-  Ability to spawn and move survivors (empty actors, dummies) with optional gear for cinematic shots. If possible, be able to pose them e.g. in high ready pose, waving, sitting etc.

- A toggle to make items in object editor either clip through other items/geometry/characters or not. For precise placement.

**Camera Tool**
- Option to freeze/unfreeze character in place while in Camera Mode. Right now poses won't work in camera mode as the character change from e.g. sit to a crouch position as soon as the camera is moved. Contrary, it would be great to have a feature for the character to move/run while the camera is moved.

- Option to set up one or several cameras, which could be toggleable and perhaps (if possible) have them panning and/or moving on a set "rail" etc. for cinematic shots.

- Blur and focus options don't seem to work. Can't mark anything as a target.

- FOV option as the previous version had (If it's in this version I may not have figured it out yet)

- Option to turn off HUD completely (removal of the center circle while in "use" mode e.g. drinking)

**Persistency**

- Change appearence on your character

- Persistency for several recording sessions. Ability to save a character, both gear and appearences.

Sorry for my several edits, I want to be as clear as possible!

**Comment by Cellander** [comment]
Great! Yeah, I figured out the FOV function. My bad. I'll try the dev branch. Thank you for helping me with a workaround on character pose freeze! Back to recording.

**Comment by cizmi3** [comment]
![image](https://user-images.githubusercontent.com/53662125/62415856-d6351800-b630-11e9-8ae3-f5912c8cb54e.png)

please help this fix!!
