### ISSUE TITLE
Buildings export is  moving a few buildings to different locations.

### ISSUE THREAD

**Issue by robotstar78** [Arkensor/DayZCommunityOfflineMode#104]

**Comment by robotstar78** [comment]
This is an odd one. We've just spent a good few hours adding in all the custom buildings we want. Exported the code and *most* of the buildings are in the right place. However, some buildings are being moved into strange places - a couple of feet etc from their correct position. Anyone know a fix for this?

**Comment by S4MT3K** [comment]
Are you „glitching“ through the buildings too?
Spawn a shipwreck part and try to walk up stairs.

**Comment by robotstar78** [comment]
We are seeing some glitching, yes. Not everywhere, but in a few places.

**Comment by robotstar78** [comment]
@S4MT3K It sounded like you might know what's wrong with your earlier comment. Is the glitching indicative of an issue i can fix?

**Comment by robotstar78** [comment]
Anyone have any ideas on this? I’d really love to get it fixed for the guys on my server :)

**Comment by S4MT3K** [comment]
Ill write a how to fix tomorrow. Iam really busy this week :/
But before i need some more infos. 

Whats in your init?

Do you run any mods?

How you spawn buildings?(especially: when theyre spawn?)

**Comment by robotstar78** [comment]
Hey man, absolutely no rush at all. I’m also busy this week, working away until Thursday now!

So we’re using DaOne’s admin tools. The latest vanilla++ mod. So the buildings are being called from the tunables.c - I export the code from COM and then change it slightly from SpawnedObject (I cant remember the exact code as I’m not at my computer) to new SpawnedBuilding (I think it’s called that anyway. Basically whatever tunables.c uses, I change it to that) I also change the “;” to “,” at the end of each line. It all goes in fine. However the Y axis often is wrong and things are constantly shifting out of alignment. Strange thing is that when I go back into COM some things have moved around again. And it’s constantly adding in one extra rogue wall in a weird place. Very odd!

No rush though man. You’ve helped me a ton in the past. Happy to wait!

**Comment by S4MT3K** [comment]
Before we Exchange too much messages on this Plattform, please add me on Steam: S4MT3Kツ
I´ll be on in about 4-5 hours.

PS: I´ll post the Solution later when i and robotstar figured it out. But its too much for now. So to reduce this message spam, we will talk private and let you guys know the solution later.

**Comment by robotstar78** [comment]
Will do chap. Monkfishywishy is me.

**Comment by sy8282** [comment]
Can I jump in here and get the solution as well
