### ISSUE TITLE
New version export code

### ISSUE THREAD

**Issue by sy8282** [Arkensor/DayZCommunityOfflineMode#105]
Anyway to change the format from the old version to the new version without manually changing every line of code

**Comment by sy8282** [comment]
changed some over to the new format but everything is out of line looks like the axis is wrong all items were placed to line up exactly (ocd) and worked fine on the old version now i have floating walls gates half in the ground any fix for this as its driving me insane

**Comment by S4MT3K** [comment]
I have the Solution. Its no issue caused by this mode. Its a problem by the mod youre using.
