### ISSUE TITLE
Where is the code kept for the custom buildings?

### ISSUE THREAD

**Issue by robotstar78** [Arkensor/DayZCommunityOfflineMode#106]
So CoM crashed on me and it lost all the custom buildings I'd previously placed. They're still on my server of course, so I'd like to copy them back into the CoM. Not sure where to put the code though? Which .C file should i be looking for?

Thanks :O)

**Comment by robotstar78** [comment]
Ok so I've found the code - it's in latest.json. Problem is that it's in a completely different format from what gets exported. Is there ANY way of importing our data into the format used in Latest.json? Please tell me there's a way otherwise I'm gonna have to start all over again!

Worried!

**Comment by DannyDog** [comment]
Exporting and saving are two different things. Saving stores those objects u placed in a json file which is then loaded back in automatically when you open singleplayer with COM again. Exporting outputs the objects into functioning code you can then use in for your server. So if you mean you want to copy the code for spawning the objects on your server and have them load into COM, then you may have a problem. Perhaps i could think of a way to allow you to load them back in that way.

**Comment by robotstar78** [comment]
Thanks Danny,
yeah, I suspected that might be what you were going to say. The .json file is empty currently (apart from a building I spawned in to see how it works) and yes, I'd very much like to be able to put back what we exported out. I realise that's probably an enormous amount of work for you though!

I'm going to ask the players on our server if they're ok with me starting again from scratch, and if not, I'll have to go through line by line and add the parameters back in manually.

Oh god, this is going to kill me!

**Comment by DannyDog** [comment]
Nah that's alright dude. I'll see about adding in the ability to do that. Gimme 24 hours :)

**Comment by robotstar78** [comment]
Ah man that would be awesome, thank you!

**Comment by DannyDog** [comment]
Done. Please download latest DEVELOPMENT branch of COM.
Take a look at what i've added here
https://github.com/DannyDog/DayZCommunityOfflineMode/commit/22c8d7946d0efec16fd66f44534c36625d7b2b6d#diff-87fa9b529718d54937dc66702c29eabeR220

**Comment by robotstar78** [comment]
Ah you absolute STAR!!!! Amaghaaadd this is going to save me at least a day of rebuilding! Massively massively appreciate it dude, thank you so much!
