### ISSUE TITLE
Would you like to add asphalt and walls?

### ISSUE THREAD

**Issue by jteles** [Arkensor/DayZCommunityOfflineMode#109]

**Comment by S4MT3K** [comment]
Download BuilderItems from the Workshop. Copy folder to Arkensors Mod, and add it into StarParameters. :D 
https://steamcommunity.com/sharedfiles/filedetails/?id=1565871491

Hug me if worked :D

**Comment by LArtDesChOiX** [comment]
Work perfect !!
BUT, when i delete an object offline, for put another build, the old objetc repop on the server ! On the add building ^^, any solution please ? Or impossible ? Need bulldozer ?

**Comment by S4MT3K** [comment]
You can search the savefile where the buildings are stored and erase it manually. You can also export the code and erase the unneeded building afterwards. I would recommened that you erase that entity in the offlinemode itself by clicking on it, erasing it and hit save.

**Comment by PhilPhonic** [comment]
Can you explain why this mod is needed for walls, but a chimney can be placed without it?
