### ISSUE TITLE
Trying to add multiple mods to Offline Mode

### ISSUE THREAD

**Issue by W41chman** [Arkensor/DayZCommunityOfflineMode#113]
I currently got 1 mod working in the Offline mode

by adding the "-mod=!Workshop\@Winter_Chernarus" to StartParameters, however i cant seem to get two mods working at the same time.. i'm not that good with code, anyone care to pitch in?

**Comment by DannyDog** [comment]
Should be !Workshop\@Winter_Chernarus

**Comment by cotohaz** [comment]
There is no more folder "mod" like in A2. Only !Workshop for me. So i tried old one: -mod@mod1
and also tried -mod=!Workshop@mod1 and just !Workshop@mod1 and that didnt work. Anyway i dosent underestand where i can place this in bat file. Like after or before other parametrs.

**Comment by S4MT3K** [comment]
Oooookayyyy read Carefully :)

Add the .pbo files (where you get them from is hopefully not a question anymore.) into a folder that is either mentioned in the mod or you just create a folder in the root directory. Shouldnt be a problem if you just name the folder @mytestmod for this example.
By the way, the ”@” is just a marker for you that you know what is a mod and what is serverfile. In the folder @mytestmod you create another folder named ”Addons”. This folder must be named Addons!!! (I suggest to write the A capital.) In this folder you add the .pbo.

In the batchfile you write the code behind the existing code: -mod=@mytestmod. If you have more mods, seperate them with an semicolon like this:

-mod=@mytestmod;@myothertestmod;testmod

How you can see it is possible to add mods wirhout an @ but i suggest to name the folder with an @. Or at least put the mod without an @ at the beginning of the -mod call.

Then hit save.

Now you have to set startparameters in steam for your game or just start dayz with installed mods. (Subscribed ones) if you Don’t use that, like me, go to dayZ in steam App rightclick on the game, go to properties, hit set launch options, and copy the code from the server batch.
Make sure you Don’t set serverside only mods in that startparameters. Actually male sure what is server mod and what is client mod ;).

Hit save. Run server, Rum dayZ, have phun, hug me if worked :)

Greetz S4MT3K

**Comment by cotohaz** [comment]
Thx for so detailed answer. Ill try it.

**Comment by FlockersDesign** [comment]
seems like its not loading mods at all anymore
