### ISSUE TITLE
Latest.json not loading

### ISSUE THREAD

**Issue by exm316** [Arkensor/DayZCommunityOfflineMode#115]
Hello all,

Im using the latest DEV Build and cant load in the json created when I hit save? Everytime I close down it loads in with a vanilla map. I am using the additional buildings mod, but dont think that should make a difference.

Could anyone help, I have large plans that I cant do in one hit and need to close down and resume at a later date.

**Comment by soaringowl** [comment]
I'm having the same problem and an additional one as well when I click export copy the code to my init.c exactly as described in the step by step. Still nothing spawns on my server

**Comment by soaringowl** [comment]
@exm316 do you think hitting export then pasting it into the init.c would make it stay next time you load it up?
