### ISSUE TITLE
Can't add custom loot (error)

### ISSUE THREAD

**Issue by soaringowl** [Arkensor/DayZCommunityOfflineMode#116]
SCRIPT (E): NULL pointer to instanceFunction: 'main'Stack trace:$CurrentDir:mpmissions\dayzOffline.chernarusplus\init.c:244

Line 244 is the code below
GetTesting().ExportProxyData("7500 0 7500", 10000); //Centre of map, radius of how far to go out and find buildings.

**Comment by HollowSurvives** [comment]
More than likely your adding this line:
`GetTesting().ExportProxyData("7500 0 7500", 10000);`
in the wrong place.

This line is exporting data from the Central Economy so if you try to export before the CE is even created it wont work.

Make sure you have the above mentioned line below the following bit of code
```
	Hive ce = CreateHive();
	if ( ce )
		ce.InitOffline();
```
also this is technically not your fault as the current documentation sort of assumes you understand what the code does here.

let us know if this sorts you out

**Comment by sashasala** [comment]
Hello, mine it works correctly but inside the export folder correctly created inside storage_XX, the file xlm is totally empty. Do you know why?

**Comment by therealZeroFox** [comment]
> More than likely your adding this line:
> `GetTesting().ExportProxyData("7500 0 7500", 10000);`
> in the wrong place.
> 
> This line is exporting data from the Central Economy so if you try to export before the CE is even created it wont work.
> 
> Make sure you have the above mentioned line below the following bit of code
> 
> ```
> 	Hive ce = CreateHive();
> 	if ( ce )
> 		ce.InitOffline();
> ```
> also this is technically not your fault as the current documentation sort of assumes you understand what the code does here.
> 
> let us know if this sorts you out

it for sure sorted me out! thank you so much man, love it!

**Comment by HollowSurvives** [comment]
For the person asking about the file being empty, you just need to leave the server running a bit longer.

**Comment by AustinLeath** [comment]
It seems as though with the new update to DayZ 1.04, "GetTesting" no longer works.

**Comment by S4MT3K** [comment]
GetCEApi().ExportProxyData( "7500 0 7500", 10000 );

**Comment by MarvinFS** [comment]
Guys any suggestions? Now on livonia server need to export custom loot maps with GetCEApi().ExportProxyData( "6500 0 6500", 6000 );
Seems not working, may be the function have changed again?
Gives me that 
when it's trying to initiate on livonia it says is logs (#2638 is a position of that function)
NULL pointer to instance
Function: 'main'
Stack trace:
$CurrentDir:mpmissions\dayzOffline.enoch\init.c:2638

definitely something has changed on new map... may the function is different now... But it's working just fine on Chernorus servers

**Comment by MarvinFS** [comment]
that's where I have it
.......
	//INIT ECONOMY--------------------------------------
	Hive ce = CreateHive();
	if ( ce )
		ce.InitOffline();

GetCEApi().ExportProxyData( "6500 0 6500", 7000 );

**Comment by keithw283** [comment]
So I got everything working correctly but the .xml file didn't copy all of my added in buildings. I let it sit plenty long enough. I checked it once and it looked full but I let it sit a couple more minutes anyways and checked again and it had the same number of lines. It found some of my custom building but not all of them.
