### ISSUE TITLE
Custom buildings loot!

### ISSUE THREAD

**Issue by Rex624** [Arkensor/DayZCommunityOfflineMode#119]
i fallowed everything on Enable loot for custom placed objects but nothing seems to  create in the storage
folder!did it step by step many times over with fewer added buildings & added but don't see anything..
i put the code under "GetTesting().ExportProxyData("7500 0 7500", 10000);  //Centre of map, radius of how far to go out and find buildings." like this  in a straight line but nothing..Buildings spawn no problem but
i'm trying to get loot in some builds is there anything i'm doing wrong?its for a rented server

**Comment by lonewolfss** [comment]
getting the same problems here not generating the export file

**Comment by lonewolfss** [comment]
ok all fixed my init.c file was layed out diffrently

**Comment by Rex624** [comment]
how did you get it to work?

**Comment by sashasala** [comment]
GetTesting functions will activate the central economy of the server that's why you need to put this line just below:

Hive ce = CreateHive();
	if ( ce )
		ce.InitOffline();
	
    GetTesting().ExportProxyData("75000 0 7500", 20000);  //Centre of map, radius of how far to go out and find buildings.

**Comment by Rex624** [comment]
I put it down like this blow all the spawn objects the sever dosent even start & no new files in storage 
being created! 

Hive ce = CreateHive();
	if ( ce )
		ce.InitOffline();
GetTesting().ExportProxyData("75000 0 7500", 20000);  //Centre of map, radius of how far to go out and find buildings.
