### ISSUE TITLE
Cannot exit menu..

### ISSUE THREAD

**Issue by Joakim67** [Arkensor/DayZCommunityOfflineMode#120]
Im running DayZ Exp. 1.0.150408 and have installed DayZCommunityOfflineMode 2.2 from Dev branch, commit d4c23e1, release note says : "Fixes for 1.0.150408".

I press "y" and the menu appears and works, but it doesnt seem possible to exit it again.
Its probably me, but please tell me how..

**Comment by BabyNades** [comment]
Same issue here.

**Comment by S4MT3K** [comment]
Im using the Same Version but does not have the issue. You pressed escape? Maybe try z instead of y (EU Keyboard layout)

However i Don’t have problems, so i cant help you guy so good. Just a suggestion. 

Greetz S4MT3K

**Comment by Joakim67** [comment]
Yes, have tried exiting the menu using both "ESC", "y" and "z".
 The menu pops up using "y", my keyboard has the "y" placed next to "t", which I guess is most normal.

I have used version 2.0 on a stable branch version not long ago, worked fine.

**Comment by Joakim67** [comment]
I have found a workaround : When in the menu, click the camera and click "toggle camera twice".
That exits the menu, but also teleports you to where you were looking, so make sure to have your character looking down before doing it.

**Comment by BabyNades** [comment]
The toggle camera twice thing works for me, thanks man! Now I can actually finish a video, cheers
