### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by bergaut** [Arkensor/DayZCommunityOfflineMode#124]
Crash at startup, before the update worked well. Is there a solution?

**Comment by polgd** [comment]
same problem here. loads forever, then finally DayZ stops responding.

**Comment by KerMod** [comment]
Same, And on other friend two. It's look like the two of us are the only ones in our community with Windows 7, and the only ones who have this issue. Maybe the same for You? @polgd @bergaut

**Comment by HeadGrowsBack** [comment]
Same problem here, again Im on Win7

**Comment by bergaut** [comment]
Installed instead of Windows 7, Windows 10, the problem is solved.

**Comment by KerMod** [comment]
Meh, I would prefer not to change my windows just for an offline mod for a Game :/ a lot of people continue to use 7, can we hope for a fix maybe? Don't know who to ask for.

**Comment by S4MT3K** [comment]
TBH the change to Win 10 isnt that bad. More capability, more Security.

And the ”flow” of the OS is almost the same as in Win 7.

Maybe watch a Video of Win 10 and then decide. 

Win 10 isnt that bad if you know what you do and what you have to if something is going on

**Comment by KerMod** [comment]
I would gladly prefer to have an update or a fix than a new OS :P Let's hope.

**Comment by andgregor** [comment]
Me too, on W7.

**Comment by KerMod** [comment]
Looks like ae maybe have a solution here. I didn't tested yet . 
https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/ 

https://media.discordapp.net/attachments/489410294360047637/548914933765767208/image0.png?width=509&height=905
