### ISSUE TITLE
[Feedback] Option to remove film grain (gamma countermeasure)

### ISSUE THREAD

**Issue by Cellander** [Arkensor/DayZCommunityOfflineMode#125]
Hi!

Is there a way to add an option to remove the film grain at dusk/dawn/night? Maybe there could be a way to toggle it ON/OFF?

Since the devs added the gamma countermeasure it's impossible to record certain scenes for cinematics and be able to maintain a clear and crisp picture.

Thanks for all your hard work!

HookOak Productions

**Comment by S4MT3K** [comment]
Try sweet fx? 🤷🏼‍♂️ Just a suggestion
