### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by EthanGibbens** [Arkensor/DayZCommunityOfflineMode#127]
Ok, so i downloaded the offline folder thing and disabled the battleye and dayz programs and files,
I copied and pasted -mission=.\Missions\DayZCommunityOfflineMode.ChernarusPlus -scrAllowFileWrite into Mission in the parameters section on the launcher, when i load up the game it sort of crashes if you look in this picture https://cdn.discordapp.com/attachments/503386175118245892/546051626033479680/unknown.png you can see in the top left my fps counter was all broken, adn the loading thing was all broke too, and it wouldnt load at all

sorry for shit english, high rn

**Comment by S4MT3K** [comment]
Ok. 
Copy DayZ and paste it anywhere.
In that new copy of DayZ go into missions folder. Erase dayzoffline.chernarusplus folder.

Download the zip of this. Extract it. Copy only the communityoffline.chernarusplus folder (or just this folder where the next folder holds all files, has to be a .chernarusplus folder)
And copy it into the folder where the dayzoffline folder was.

Rename DayZ_Be.exe to DayZ_BE.disabled
And the battleye folder to battleye.disabled.

Go into the missionfolder and run the batchfile. Should work.

Make sure youre not running any beta programms from dayZ. You need the vanilla DayZ!

Hope it will help you.

Greetz S4MT3K

**Comment by Joarius** [comment]
Hi.
I have the same problem :
- I have copied/pasted DayZ Game in another place.
- I have erased the folder _dayzOffline.ChernarusPlus_.
- I have pasted DayZ.Community.OfflineMode.
- DayZ_Be.exe is renamed DayZ_BE.disabled and the Battleeye folder in Battleye.disabled.
But it doesn't work. :\

In previous attempts, with "originel" game and via Launcher, i had [this](http://image.noelshack.com/fichiers/2019/07/6/1550314783-dayzcommunityofflinemode-erreur-01.png).

I precise that before update of DayZ, i could launch solo mission and use your mod. :)

**Comment by polgd** [comment]
same exact issue. followed instructions precisely, over and over again with each branch version following all methods of use over the span of multiple days, always using the correct download version and correct dayz version. hours trying, yet no luck. "DayZ has stopped responding". it'll haunt my dreams. used to work fine too.
