### ISSUE TITLE
Cannot Convert Int to String.

### ISSUE THREAD

**Issue by S4MT3K** [Arkensor/DayZCommunityOfflineMode#128]
Cameratool.c Line 345: Cannot Convert "int" to "string" for argument "0" to method "getAction();

When i convert it to a string i cant move: No keyboard or Mouse input. I can look to fix it if you want. But im Busy... so probably its better you take a look...

**Comment by Arkensor** [comment]
Is this still an issue?

**Comment by S4MT3K** [comment]
Sry for the late response.
Got busy. 

The issue was gone with the 1.02 update.

But has Overwritten all my DayZ keybinds.

So anything weird was going on. The new version works like a charm. 

So Can be closed and forgotten. 

I‘ll have an eye on it and watch for familiar issues... 

Greetz S4MT3K
