### ISSUE TITLE
Can´t save placed Objects (SOLVED)

### ISSUE THREAD

**Issue by nickmuenster** [Arkensor/DayZCommunityOfflineMode#131]
it says objects are saved to latest.json 

1. i dont have the file
2. nothing is saved

i dont want to export the objects every time i close. i want a safegame for the buildings i have placed. is that possible? is there a fix for that?

or..is there a workflow for editing objects you have once placed / exported and posted into the ini.c

**Comment by S4MT3K** [comment]
Maybe create a filestructure on your own?

Document->DayZ->CommunityOfflineMode->Scenes

**Comment by nickmuenster** [comment]
that dosent work, i tryed:
C:\Users\nickm\Documents\DayZ\CommunityOfflineMode\Scenes

and 

D:\Steam\steamapps\common\DayZ\CommunityOfflineMode\Scenes

but it dosent want to save :/

**Comment by S4MT3K** [comment]
Hmmm. But you have copied dayz, disabled battleye by renaming the files and folders? And you have changed nothing else?!? Then it should work. Try to set it up again, download latest version from here. Follow Instruction strictly.

**Comment by nickmuenster** [comment]
OH YEAH! Thank you so much.. i didn´t read the Instructions carefully. Now everything works, keep up the great work. SOLVED!
