### ISSUE TITLE
Drybags wont bury

### ISSUE THREAD

**Issue by Dumpgrah** [Arkensor/DayZCommunityOfflineMode#134]
when burying a drybag it creates the stash dirt pile but leave the drybag on ground above dirt pile. when
I dig up said stash it gives nothing. same with seachest also, i assume with all containers that you can bury. i can bury said things on the server i play on just not in this community offline mode

**Comment by Dumpgrah** [comment]
just woundering if this is really a problem or are you working on it? or is it bohemia that needs to fix it?

**Comment by Arkensor** [comment]
It's something for BI.
