### ISSUE TITLE
DayZ Crashing At Launch

### ISSUE THREAD

**Issue by Wolmf** [Arkensor/DayZCommunityOfflineMode#136]
I've followed the instructions countless times rechecking everything to make sure I did it all correctly. I've even gone through and installed the different branches of the mission. Nothing seems to work. I launch the batch file and it goes into the DayZ loading screen and stays there for about 5-7 minutes and it crashes stating that "DayZ_x64.exe has stopped working" and prompts you to close the program.  I've even gone through and uninstalled DayZ and reinstalled it multiple times on different hard drives.

Here is the crash log I keep getting:

Log C:\Users\REDACTED\AppData\Local\DayZ\crash_2019-03-14_01-31-05.log started at 14.03. 01:33:43

REDACTED-PC, 14.03 2019 01:33:43
NULL pointer to instance
Class:      'ModuleManager'
Function: 'GetModuleByName'
Stack trace:
$CurrentDir:missions//DayZCommunityOfflineMode.ChernarusPlus//core//ModuleManager.c:201
$CurrentDir:missions//DayZCommunityOfflineMode.ChernarusPlus//core//CommunityOfflineClient.c:106
scripts/3_Game/dayzgame.c:728

Runtime mode
CLI params: mission .\Missions\DayZCommunityOfflineMode.ChernarusPlus scrAllowFileWrite  nosplash  noPause  noBenchmark  scriptDebug true filePatching  doLogs

I might have done something wrong, but I am atleast 75% sure I did it right. I've given up and decided to ask for help. Thanks for any help anyone can give.

**Comment by illicious** [comment]
Same problem. Game ran just fine about a month and a half ago.

XXXXXXXXX, 14.03 2019 05:17:20
NULL pointer to instance
Class:      'ModuleManager'
Function: 'GetModuleByName'
Stack trace:
$CurrentDir:missions//DayZCommunityOfflineMode.ChernarusPlus//core//ModuleManager.c:201
$CurrentDir:missions//DayZCommunityOfflineMode.ChernarusPlus//core//CommunityOfflineClient.c:106
scripts/3_Game/dayzgame.c:728

Runtime mode
CLI params: mission .\Missions\DayZCommunityOfflineMode.ChernarusPlus scrAllowFileWrite  nosplash  noPause  noBenchmark  scriptDebug true filePatching  doLogs
