### ISSUE TITLE
Spawn as a specific character 

### ISSUE THREAD

**Issue by alphagamer1981** [Arkensor/DayZCommunityOfflineMode#138]
Hi there, I am doing a video project and I want to have my specific character (SurvivorM_Peter) to spawn instead of random ones, it takes ages to cycle through all of them so what is the code to edit in the staticfunctions.c to get this, i did notice the line

static PlayerBase CreateCustomDefaultCharacter()
{
    PlayerBase oPlayer = PlayerBase.Cast( GetGame().CreatePlayer( NULL, GetGame().CreateRandomPlayer(), GetSpawnPoints().GetRandomElement(), 0, "NONE") );

so i assume i need to change this to something

**Comment by wriley** [comment]
Replace GetGame().CreateRandomPlayer() with your desired character name

PlayerBase oPlayer = PlayerBase.Cast( GetGame().CreatePlayer( NULL, "SurvivorM_Peter", GetSpawnPoints().GetRandomElement(), 0, "NONE") );
