### ISSUE TITLE
Don't work for me 

### ISSUE THREAD

**Issue by Pumking24** [Arkensor/DayZCommunityOfflineMode#14]
Hi,
I have an issue, when i start the game with DayZ_x64 the game lauch online and the mod basically doesnt work, however when i use steam and choose to lauch in solo, there's just the plain sky background and i cant do anything.
Hope you can help me, just want to try this cool mod 
Thanks in advance

**Comment by Pumking24** [comment]
yes

**Comment by Arkensor** [comment]
Can you delete the entire dta folder and missions folder inside dayz, validate your files in steam and try the official offline mode again?

If that works out we'll figure out why this mod isn't working as intended.

**Comment by soldierofthemaxx** [comment]
this does not work for me as well, instructions are clunky and unclear,
The DayZ_x64.exe starts online mode not offline mode, you have to right click in your gamelist on steam to go into offline mode.

 When unzipping the .zip file the file reads DayZCommunityOfflineMode-master, are you only suppose to transfer the contents inside the file over or the whole file, instructions are very unclear on what to do?

**Comment by Pumking24** [comment]
Hi,
Just tried with the new update 1.5 and it didnt worked, i will reinstall the whole game and tried it again but i dont have high hope, sometimes mods just dont work, thanks anyway and great job

**Comment by raxto** [comment]
There was new update today, 1.5 is old version.

**Comment by Pumking24** [comment]
yes, i am talking about this one and it is indicated as the latest

**Comment by raxto** [comment]
sry i talked about DayZ update.

**Comment by Pumking24** [comment]
np

**Comment by raxto** [comment]
I mean that 1.5 is old and maybe it will not working with new DayZ update from today.

**Comment by Arkensor** [comment]
On it atm, give me a bit of time and i'll push a version that does not manipulate the game files anymore ;=) That should work flawlessly for you

**Comment by Pumking24** [comment]
Nice ! very excited ! :)

**Comment by Pumking24** [comment]
It worked but somehow i got zombies and loot drop in balota airfield, pretty funny. Thank you for this mod

**Comment by Arkensor** [comment]
Have you used the latest 1.6 release ? If so yes zombies and loot spawn now
