### ISSUE TITLE
Export /mapgroup

### ISSUE THREAD

**Issue by sashasala** [Arkensor/DayZCommunityOfflineMode#141]
Hello everyone, once i place the object, i correctly get the "export" folde inside storage_XX but the file mapgroups.xlm inside is alwasy empty even if i placed plenty buildings in the map.

thanks in advance for the clarification

**Comment by Arkensor** [comment]
Hi,

please try the latest update and see if it's working then or not.

**Comment by HollowSurvives** [comment]
Leave the server running for a bit, the file is created quickly but can take a little while to fill
