### ISSUE TITLE
add items to offline init.c?

### ISSUE THREAD

**Issue by EvilAnimal** [Arkensor/DayZCommunityOfflineMode#145]
I took the items and put them in the "DayZCommunityOfflineMode" init.c to see if I could add a couple additional items but wanted the other items for reference. The game crashes. Is it possible to load them in the offlinemode mission?

I put the helper function at the start of the init.c and the items in the "Void main ()"

**Comment by ThaiTemptation** [comment]
Was hoping someone could have answered this. I also would like to get the current addons into the "DayZCommunityOfflineMode.ChernarusPlus" mission for adding additional items. I added the helper and reguardless of where I place this it will start. Adding any "spawnitems" into the "void main ()" crashed me to the desktop without an error.

**Comment by S4MT3K** [comment]
Where you got This Items from, and what are you trying to do?
What do you mean exactly with "helper"?

Show a screen with the crash.
Show added code and tell me in which file you did put that.

Answer all questions please otherwise i cant help you!

**Comment by Arkensor** [comment]
The helper function does not belong into the void main itself. It needs to be placed outside of it. Please see the code examples from this guide: https://github.com/Arkensor/DayZCommunityOfflineMode/wiki/Add-custom-objects-to-your-server-or-mission#step-7
