### ISSUE TITLE
Total black screen at start

### ISSUE THREAD

**Issue by remozserver** [Arkensor/DayZCommunityOfflineMode#146]
Hello,
i've updated this amazing mod on my development rig, but can't start because the screen still all black when enter in offline mode (i had no problems with previous version for dayz 1.01, for updating i've removed old folder and extracted the new by the new zip download for 1.02)

See image: http://i65.tinypic.com/ra70gy.png

Thank you so much,
bye

Remoz

**Comment by JeromeK13** [comment]
Hey 
This can be fixed when using the dev-version 

Greets
JeromeK

**Comment by Arkensor** [comment]
It still happens from time to time for me. I will try and address this issue in the future. For now, you just need to restart until it works.

**Comment by ktulm** [comment]
for me, black screen from time to time in offline mode was caused by hardware antialiasing. i disabled it in video otpion in dayz and it solved the problem
