### ISSUE TITLE
Suggest update to the Wiki on "Enable loot for custom placed objects"

### ISSUE THREAD

**Issue by hlyl** [Arkensor/DayZCommunityOfflineMode#148]
Can I suggest that you highlight that the function:
GetTesting().ExportProxyData("7500 0 7500", 10000);  //Centre of map, radius of how far to go out and find buildings.

should be placed after the economy has been initiated, I had to do a lot of investigation to figure this out.

**Comment by Arkensor** [comment]
Thank you for your feedback. The wiki page has been updated.
