### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by MarkusCZ** [Arkensor/DayZCommunityOfflineMode#150]
Hello, im pretty new to these scripts, everythings is working for me but is there someone who would write me a guide on how to add mods to the offline mode? And other question is how to spawn weapons with all the attachments? is there a way to do that too?

**Comment by S4MT3K** [comment]
Simply like you do that with the Server.
Add to the start batch:

-mod=
And then your mods. Mostly the mods beginning with an @ some can have none. However just write how they named like this:

-mod=@mod1;@mod2;@mod3

But rename them. Seperate multiple mods with semicolon.

To spawn a fulleqip weapon requires a codechange and is a bit more tricky than adding mods.

You could write a plugin that Does that.

I dunno if DaOne has still the history on his github repo, there were a lot of code in the closed issues. Youll find a lot of my code there. Somewhere there is a codesnippet to spawn a full equip m4.

But this also requirres a admin tool. So i recommend to choose a Tool from The Workshop, or just use arkensors Spawnmenu. Its easy to handle, super efficient and nice to look.

**Comment by MarkusCZ** [comment]
> Simply like you do that with the Server.
> Add to the start batch:
> 
> -mod=
> And then your mods. Mostly the mods beginning with an @ some can have none. However just write how they named like this:
> 
> -mod=@mod1;@mod2;@mod3
> 
> But rename them. Seperate multiple mods with semicolon.
> 
> To spawn a fulleqip weapon requires a codechange and is a bit more tricky than adding mods.
> 
> You could write a plugin that Does that.
> 
> I dunno if DaOne has still the history on his github repo, there were a lot of code in the closed issues. Youll find a lot of my code there. Somewhere there is a codesnippet to spawn a full equip m4.
> 
> But this also requirres a admin tool. So i recommend to choose a Tool from The Workshop, or just use arkensors Spawnmenu. Its easy to handle, super efficient and nice to look.

Ok thanks :) you can close this
