### ISSUE TITLE
COMKeyBinds.c Line 255 Suppressor Repairing seems to be Broken?!?!

### ISSUE THREAD

**Issue by S4MT3K** [Arkensor/DayZCommunityOfflineMode#151]
Suppressor is not Repaired after Pressing R.

I also tested the Function on an Independed platform and there is also no Result. Suppressor Keeps Broken.
Weapon is Repaired and magazine is Reloaded, but the Suppressor takes no Effect.

Greetz S4MT3K

**Comment by Arkensor** [comment]
Thank you for the report. This has been fixed now.
