### ISSUE TITLE
Export is moving buildings to different locations

### ISSUE THREAD

**Issue by DeliciousAce** [Arkensor/DayZCommunityOfflineMode#152]
I already mapped a lot in the past on the DayZ Amra II Mod, there was a similiar Problem like this one, but the Buildings just moved a bit by saving the Project.
Now we spent a good few Hours on the Chernarus Plus Map by adding a few custom Buildings. 
After we Exported the Code, most of the buildings are not in the right place. 
Some of the buildings are being moved a couple of feet from their correct position. 
I tryed also that no Building is touching other stuff, to Prevent collisions and also started all from Scratch just to put one Building for testing Purpose. And still the same Problem....

It is slowly frustrating Me, also to see that there was already an issue with the same Problem,
where the Dude was Told to add one of you guys in steam to solve the Problem.
Well i do not think that this is the Right way to handle such Things, cus i can not read what solution you guys told to him via steam, instead of Posting such important stuff here.

So, Anyone know a fix for this or a solution to Prevent it?
And where i can find the latest.json File?

Thanks in Advance, Regards Ace

**Comment by DeliciousAce** [comment]
Here a Pic how i placed the Building via the COM:
https://steamcommunity.com/sharedfiles/filedetails/?id=1740948327

And here one that Shows the result after Exporting it and loading on our Test Server:
https://steamcommunity.com/sharedfiles/filedetails/?id=1740948303

I just want to know why is this Happening.

**Comment by NTX-Nitrix** [comment]
Hello, I am that friend you are talking about but it is not the same problem that you have.

I do not know if you downloaded COM in the last 2 days or you already had an older version of COM since it has been modified 2 days ago.

If you downloaded it 2 days ago, the .json file is created in the My Documents / DayZ or where your game has created your player profile.

**Comment by DeliciousAce** [comment]
No idea if you are the friend, the usernames do not match.
Here is the issue Post what i talk About:
https://github.com/Arkensor/DayZCommunityOfflineMode/issues/104
I downloaded the COM on May 13 at 6 o'clock in the morning.
Thanks I had totally overlooked since the file is saved with the name COMObjectEditorSave.json.
I will now download the COM Files again and test it.

Thanks for your answer, I appreciate that very much.

**Comment by DeliciousAce** [comment]
I installed COM again but the Objects are still not in the Position where i placed them.
It seems like the objects are saved in the position where I spawn them on the first time, the subsequent change of the position does not seem to be saved.

**Comment by NTX-Nitrix** [comment]
When you press Control + S, make a copy to the clipboard.
and it looks like that
// Spawn helper function
void SpawnObject (string type, vector position, vector orientation)
{
    auto obj = GetGame (). CreateObject (type, position);
    obj.SetPosition (position);
    obj.SetOrientation (obj.GetOrientation ()); // Collision fix
}

// Your custom spawned objects
SpawnObject ("Land_Wreck_Ikarus", "13612.858398 29.004204 11807.856445", "2.000000 -10.000000 14.999998");

If you put in your init.c the Spawn helper function as seen above the objects will be wrong.
You have to put this in your init.c

// Spawn helper function
void SpawnObject (string objectName, vector position, vector orientation)
{
    Object obj;
    obj = Object.Cast (GetGame (). CreateObject (objectName, "0 0 0"));
    obj.SetPosition (position);
    obj.SetOrientation (orientation);

    // Force update collisions
    if (obj.CanAffectPathgraph ())
    {
        obj.SetAffectPathgraph (true, false);
        GetGame (). GetCallQueue (CALL_CATEGORY_SYSTEM) .CallLater (GetGame (). UpdatePathgraphRegionByObject, 100, false, obj);
    }
}

So it is in the instructions of the Github.

https://github.com/Arkensor/DayZCommunityOfflineMode/wiki/Add-custom-objects-to-your-server-or-mission

**Comment by DeliciousAce** [comment]
Thank you for giving me this Hint with the void SpawnObject :)
It is working now, next time i should take a break for a longer nap :P

I appreciate your help very much!

Regards Ace
