### ISSUE TITLE
Not able to see a few selected Items and Objects 

### ISSUE THREAD

**Issue by DeliciousAce** [Arkensor/DayZCommunityOfflineMode#153]
I try to find out in COM the Classnames of some Items and Objects.
But not at all Objects I can get the Name displayed, specially the Sandbag 
and the other Military barricades.
I've gone through all the steps from COM Wiki, the Video of Not A Bannana and Bonnnetwork.
It seems like not even the Mods are loaded, although they were adjusted according to the available instructions.

In The COM .bat File i have entered this Parameter:
-mod=@BuilderItems;@BuilderStatics
Even the try with the quotes it does not work.
I also tried it via the Settings in Steam, where I had set the Launch Parameter.

I do not even know if I'm doing something wrong or which guide I should use.
It would be helpful and nice of you if you can include in your installation instructions an additional appendix for how to start COM with Mods.

Thanks in Advance, Regards Ace

**Comment by NTX-Nitrix** [comment]
This is my line in the .bat
I have the mods copied in the DayZ folder

start D:\DayZ\DayZ_x64.exe -mission=D:\DayZ\Missions\DayZCommunityOfflineMode.ChernarusPlus "-mod=@BuilderItems;@Evocatus Billboards & Signs;@LG Custom Billboards" -scrAllowFileWrite -nosplash -noPause -noBenchmark -scriptDebug=true -filePatching -doLogs

**Comment by DeliciousAce** [comment]
Thank you very much, will try it again and give feedback.

Regards Ace

**Comment by DeliciousAce** [comment]
Seems to be fixed, i just installed all Files fresh and seems to work now.

Thanks.
