### ISSUE TITLE
Problem with ModuleManager.c

### ISSUE THREAD

**Issue by Extelfel4320** [Arkensor/DayZCommunityOfflineMode#156]
Can't compile mission init script
$CurrentDir:missions//DayZCommunityOfflineMode.ChernarusPlus//core//ModuleManager.c(88): Undefined function 'UpdateControls'
How can i solve it?
![bQhFjx_81xE](https://user-images.githubusercontent.com/50752310/57950922-50d37e80-78f1-11e9-8486-bef35a02e572.jpg)

**Comment by Arkensor** [comment]
Hello,

which version of the game are you using?

**Comment by murakus** [comment]
I'm getting similar errors and I'm using version 1.0.15 full ofline test version.

**Comment by T-Obi** [comment]
Hey Guys, 

I get a similar error when start the game:

![image](https://user-images.githubusercontent.com/53126213/61583284-46727280-ab36-11e9-80d5-a10add1a7b46.png)

Anyone an idea ???

Thanks for help

**Comment by neil501** [comment]
yeah i used to get them too until i found a fix for it! What you need to do is find the older version of Arkensor/DayZCommunityOfflineMode it's not called Arkensor The name of the file i used to get my offline game working so i can use the spawn items was the file called EMU/DayZCommunityOfflineMode download that then

**Comment by neil501** [comment]
I went to this dayz site-Download from this website- https://github.com/EmuZONE/DayZCommunityOfflineMode/tree/464ee4b04580f31d34d15abf6b93c997cd9cd585/Missions/DayZCommunityOfflineMode.ChernarusPlus
The file should read "EmuZONE/DayZCommunityOfflineMode"  this is the older working one.The newer one called "Arkensor" DIDNT WORK for me! So watch what you download took a while for me to realize it was the file that needed changing and was the whole reson i wasnt able to play anyway good luck! If you have any problems after this i'll go into exactly everything i did to get my game to work but this should get you up and running! Have fun!

**Comment by Arkensor** [comment]
This is a completely outdated fork of my project. Do not use it!

The fix was deleting an outdated version for a different stable build ... the current public builds works perfectly fine
