### ISSUE TITLE
Weapon Issue? 

### ISSUE THREAD

**Issue by cmen277** [Arkensor/DayZCommunityOfflineMode#158]
Hi,

i really like the Offline Mode for testing, but some Weapons are "broken" 

weapons like the AK101, Bow, Crossbow Double Barrel Shotgun, are not useable, i cant reload and the whole inventory interfaces freezes.

is this a Bug that only is on my machine, or are some weapons in the offline Mode just broken?

greetings, and keep up the good work!

edit: oh i forget to ask
is there a Function so save and load the Equipment?

**Comment by Jacob-Mango** [comment]
Those weapons aren’t meant to be used. The developers have not yet re-implemented them into the game.
