### ISSUE TITLE
m_bloaded

### ISSUE THREAD

**Issue by dosserua** [Arkensor/DayZCommunityOfflineMode#159]
![image](https://user-images.githubusercontent.com/11022698/58257383-7e00b080-7d79-11e9-9177-bbca6c875293.png)

patch 1.03

**Comment by Arkensor** [comment]
Please check if this issue happens for you with the latest release.

**Comment by dosserua** [comment]
> Please check if this issue happens for you with the latest release.

the same mistake, it is worth the new version, the connected mods - CF and Community Online Framework and Builderitems
