### ISSUE TITLE
Does not seem to work anymore

### ISSUE THREAD

**Issue by soldierofthemaxx** [Arkensor/DayZCommunityOfflineMode#16]
this does not work for me as well, instructions are clunky and unclear,
The DayZ_x64.exe starts online mode not offline mode, you have to right click in your gamelist on steam to go into offline mode.

When unzipping the .zip file the file reads DayZCommunityOfflineMode-master, are you only suppose to transfer the contents inside the file over or the whole file, instructions are very unclear on what to do?

**Comment by neonoxd** [comment]
Clunky and unclear? What the hell :D

**Comment by Nitr0o** [comment]
Works fine for me!

**Comment by soldierofthemaxx** [comment]
after finally getting it to run,
following corresponding commands don't work.
delete.
end.
insert.

k - command works
spawn commands works
b works

**Comment by Nitr0o** [comment]
How would you explain its working fine for me and not for others? I downloaded the same files, and "followed" the Instructions and it works, no smartarse, as you put it, about it. Just stating fact, a fact that might help to sort your issue. Twice you have been rude for no reason, I'm not sure what your problem is? We are all wanting this to work, and help get the issues sorted.

**Comment by soldierofthemaxx** [comment]
twice you have been rude too whats your point lol

**Comment by Nitr0o** [comment]
@soldierofthemaxx have you tried using one of the previous releases? Might help narrow the issue down?

**Comment by soldierofthemaxx** [comment]
there  was a small patch this morning that updated could this be the cause?

**Comment by neonoxd** [comment]
well that very well could be, cause if they changed scripts.pbo then the content uploaded here is outdated

**Comment by Arkensor** [comment]
Patching it atm

**Comment by Arkensor** [comment]
Should be patched now on the latest release

**Comment by Arkensor** [comment]
@soldierofthemaxx Redownload the latest release now and read the instructions on how to install things now. I have made it easier hopefully ;)
