### ISSUE TITLE
Search not working.

### ISSUE THREAD

**Issue by raxto** [Arkensor/DayZCommunityOfflineMode#160]
Search by class name not working.

**Comment by S4MT3K** [comment]
Can you be a bit more specific? 
Do you mean when you type into the search bar for example: land_wreck, that it isnt showing you anything?

**Comment by raxto** [comment]
yes, thats it. Before it was instant fulltext search. Now not working.

**Comment by S4MT3K** [comment]
Can you just try to Install the Editor again?

Maybe something went wrong with the new hotfix from dayz or you made a little mistake or your computer just said ”no”.🤪

I tested it and i can search properly 🤔

So maybe a fresh install can help.

If it is still happen, i explain you the next steps... but for now i assume a reinstall would help.

**Comment by raxto** [comment]
Reinstalled working. thx
