### ISSUE TITLE
Wrong Orientation

### ISSUE THREAD

**Issue by Threvan** [Arkensor/DayZCommunityOfflineMode#161]
I placed down the objects and exported.
Then I pasted it on another PC with the host.
When I enter the server, the objects are in the right places I putted them but faces other sides. 
Oonly one or two are faced the way I placed them.
Someone knows what happened?

Everything works fine, only the rotation is wrong.

**Comment by S4MT3K** [comment]
What buildings are wrong?
The same building alle the time or is this happen Randomly?

Is this object an mod implemented object or is it in the Basegame?

**Comment by Arkensor** [comment]
Hello,

can you please send the .c files that contain your object spawn code?

**Comment by WCSarris** [comment]
It looks like I am having the same issue as well. Went into free cam mode, placed a variety of objects for a base, exported and placed the new objects in the init.c as required, and started up the server. All objects are there, but the rotations are all off.

**Comment by S4MT3K** [comment]
As Arkensor asked, can you send the .c file that contain your spawn code? Or at least copy and paste it, if you have problems or dont know how to upload.

**Comment by WCSarris** [comment]
> As Arkensor asked, can you send the .c file that contain your spawn code? Or at least copy and paste it, if you have problems or dont know how to upload.

Converted to .txt document so it can be attached directly to comments.

[init.txt](https://github.com/Arkensor/DayZCommunityOfflineMode/files/3287631/init.txt)

**Comment by WCSarris** [comment]
@S4MT3K @Arkensor Here is a fix I found on Youtube.

For those that had issues with this... simply remove "obj.GetOrientation()" with "orientation" in the "SpawnObject()" parameter that you place at the top of the init.

I can confirm this also worked with mine. There is one other issue I have noticed.... AI like zombies, wolves, etc. Will walk right through placed buildings. Is there a workaround for this?

Thank you!

**Comment by BrutalBirdie** [comment]
> For those that had issues with this... simply remove "obj.GetOrientation()" with "orientation" in the "SpawnObject()" parameter that you place at the top of the init.

This would be the right helper function
```
//Spawn helper function
void SpawnObject( string type, vector position, vector orientation )
{
    auto obj = GetGame().CreateObject( type, position );
    obj.SetPosition( position );
    obj.SetOrientation( orientation ); //Collision fix
}
```

**Comment by Arkensor** [comment]
Has been updated in the latest dev version and will be live in the next update.
