### ISSUE TITLE
Zombies walk through buildings

### ISSUE THREAD

**Issue by Sigworth** [Arkensor/DayZCommunityOfflineMode#162]
I got my buildings in my server and they spawn loot but zombies just walk through the walls.
void SpawnObject( string type, vector position, vector orientation )
{
    auto obj = GetGame().CreateObject( type, position );
    obj.SetPosition( position );
    obj.SetOrientation( orientation ); //Collision fix
}

**Comment by WCSarris** [comment]
I am experiencing the same issue as well.

**Comment by Grant-Sweat** [comment]
I'm having this issue as well.

Seems to happen to even normal zombies, not just Zomberry spawned zombies.

**Comment by Arkensor** [comment]
I have updated the SpawnObject function, to hopefully address this issue. Please check the latest version on the development branch to see if it works.
