### ISSUE TITLE
Rework placed object

### ISSUE THREAD

**Issue by xKaZaRx** [Arkensor/DayZCommunityOfflineMode#163]
Hi, 
Everything works perfectly and this tool is great to customize the map.
There is one thing i can't find how to do tho. I have export my buildings in a file and clear the building list ingame. I'm now starting the mission with a "custombuilding.c" file. 
But what if i want to change buildings position again ? how do i put them back in the ingame buidling list ? 

Thanks for reading this. Great work, best regards

**Comment by S4MT3K** [comment]
Start the Game with your CustomBuildings like you would start your server.

Once the Buildings are loaded you can delete the existing property and place it new. Then you can change their position, export that code and replace it in you custombuilding.c
I recommend that you first seperate that code you want to change in your custombuilding.c that you can easyliy change it. And do not change that much at once. Pick up little sections. 

Ps: Bit of Code understanding is assumed.

Greetz S4MT3K

**Comment by x-KaZaR-x** [comment]
Alright thanks S4MT3K for your help ! 
Have a good one :)
