### ISSUE TITLE
Offline mode crashes

### ISSUE THREAD

**Issue by DayZPro** [Arkensor/DayZCommunityOfflineMode#164]
When I start offline mode dayz, it crashes before it starts.
Please help.

**Comment by Arkensor** [comment]
Please try this: https://github.com/Arkensor/DayZCommunityOfflineMode/wiki/Toggle-loot-and-infected-spawn and see if it helps

**Comment by PapaKhanZ** [comment]
Why close this it still does it. I was using it yesterday went to bed woke up and now cannot get in WTF?
