### ISSUE TITLE
New Version Offline Mod

### ISSUE THREAD

**Issue by murakus** [Arkensor/DayZCommunityOfflineMode#165]
Are you planning to design a new offline mode for DAYZ ??  version 1.0.15 for example.

**Comment by Arkensor** [comment]
What exactly do you mean with a new offline mode? Is there something you are currently missing, that you would like me to add to the offline mode?

**Comment by murakus** [comment]
I'm using version 1.0.15 and undefined function errors. for example camere Tool erorrs.

**Comment by Arkensor** [comment]
What do you mean with 1.0.15? Neither the game or my mission currently has a version 1.0.15

**Comment by murakus** [comment]
http://i67.tinypic.com/257q29v.png how can I solve this problem ?

**Comment by murakus** [comment]
I have a dayz version running without steam. Offline version dayz 1.0.15...DayZCommunityOfflineMode 2.8 gives some errors. error: Undefined Functions ... Camera Module for example. Is there a solution to this ? thank you.

**Comment by Arkensor** [comment]
I have no intention to support cracked versions of the game.

**Comment by sherinfawzy2** [comment]
Hi

**Comment by sherinfawzy2** [comment]
I have the official version of steam, but I have the same problem
