### ISSUE TITLE
Is it Possible to turn off infinite ammo?

### ISSUE THREAD

**Issue by AydenDev** [Arkensor/DayZCommunityOfflineMode#170]
This is not really an issue, but it would be cool if the "press r to infinitely reload your weapon" even without godmode, could be turned off to give a more realistic feel, where you actually have to load the bullets back into the magazine.

**Comment by Arkensor** [comment]
You can disable it by removing this line: https://github.com/Arkensor/DayZCommunityOfflineMode/blob/master/Missions/DayZCommunityOfflineMode.ChernarusPlus/core/modules/ComKeybinds/COMKeyBinds.c#L56
