### ISSUE TITLE
DayZ Keeps crashing upon opening

### ISSUE THREAD

**Issue by DatGuySyl** [Arkensor/DayZCommunityOfflineMode#172]
Everytime I try to open the offlinemode It keeps loading and then shuts it off. I've tried disabling the HIVE_ENABLED but this hasn't changed anything. I run on the latest version. #172

**Comment by Arkensor** [comment]
Nothing I can do there. Maybe you do not have enough ram? You need at least 16GB.

**Comment by nahkranoth** [comment]
I ran into the same issue, saw in the logs that the "server" couldn't access some files. Ran the .bat as administrator and it solved all the problems.
