### ISSUE TITLE
Mods not loading propertly

### ISSUE THREAD

**Issue by MarkusCZ** [Arkensor/DayZCommunityOfflineMode#173]
Hello, I have a little problem when running modded guns and clothing. I use the -mod parameter correctly but when in game I spawn a modded gun like the Golden Desert Eagle it just says the $INT$ name before the name of the weapon and I cannot pick it up or do anything with it. (The gun is from @WeaponReduxPack and yes I use all the other mods it needs to work..)

**Comment by Arkensor** [comment]
Has nothing to do with the offline mode.

**Comment by MarkusCZ** [comment]
Yeah i know but i think im doing something wrong because every mod does this not just only this one.

**Comment by ChoppedCow** [comment]
I have this same problem!
