### ISSUE TITLE
Is there any way we can get more free camera controls?

### ISSUE THREAD

**Issue by NachoNinjaGnome** [Arkensor/DayZCommunityOfflineMode#175]
In many editors, there are functions to raise and lower your altitude.  Spacebar and Ctrl are good choices for these functions, spacebar to raise and ctrl to lower.

Also, something to slow movement.  The default movement speed is pretty fast and holding Shift makes it even faster.  Maybe we can get Caps Lock to slow it down?  It would help immensely for a variety of efforts.

**Comment by Sevenlife7** [comment]
If you press the right click and scroll wheel down, you will slow down the cam movement, and scroll wheel up, to speed it up :)

**Comment by Arkensor** [comment]
There are currently no plans to expand on the freecam functionality. This might change with a major rework, but that is not coming any time soon.
