### ISSUE TITLE
Backup problem

### ISSUE THREAD

**Issue by Vazymolo** [Arkensor/DayZCommunityOfflineMode#176]
Hello everyone,

After placing buildings and objects, I save to put the file in the game, everything works perfectly.
But here I have a problem, the game crash, and when I restart it, everything is gone.
I started to map again, and I lost everything again (I did not click on "clear")
I have the text file of the buildings / objects, but I can not find the file or replace the text file.
Can you help me?
thank you !

**Comment by Vazymolo** [comment]
Ok, but..where?

**Comment by Arkensor** [comment]
The file everything is beeing saved in is C:\Users\XXXXXX\Documents\DayZ\COMObjectEditorSave.json

If you crash this file will not be written. I suggest to save regularly and export the code and save the export somewhere just to be safe.
