### ISSUE TITLE
barracks interior.

### ISSUE THREAD

**Issue by bobbenx** [Arkensor/DayZCommunityOfflineMode#178]
So ive placed a bunch of items. put em in the init.c put in the thingie to get the export for loot and all of that is working flawlessly. however. the interior in some of the buildings ive placed is not working. the chairs tables etc that are in em by default arent visible. they still got collision and shadows. yet i cannot see em. what exactly am i doing wrong? one of the buildings in question is the Land_mil_barracks6
some other buildings seems to be missing doors and stuff. ive got bldr items on the thing but i havent found an object for those buildings i can place inside of em. halp please :P

**Comment by Arkensor** [comment]
I can't really help there. Please try only loading one house with the interior as a test and see if that works reliable.

**Comment by S4MT3K** [comment]
I had the same issue, make sure you have everything correct implemented.

Make sure bldr is called correctly :)

**Comment by bobbenx** [comment]
allright i deleted basicly everything downloaded the newest version. and started from scratch, spawned 1 building and ive got the same issue as before. objects inside buildings just have a shadow on the floor and they got collosion but they are invisible. this is in the offline mode itself btw. i havent tried pushing it to my actual server yet. do they just not have those objects visible inside the offline mode or ?
i my command line looks like this
start DayZ_x64.exe -mission=.\Missions\DayZCommunityOfflineMode.ChernarusPlus -nosplash -noPause -noBenchmark -filePatching -doLogs -scriptDebug=true "-mod=@BuilderStatics;@BuilderItems"
i have also tried reversing the 2 mods so items is first and statics is behind. regardless of what i do i keep having this issue. im running out of hair i can pull out at this point. any pointers would be greatly appreciated.

**Comment by bobbenx** [comment]
I managed to figure out the issue. if i unload builderstatics everything works like it should yay! sorry for being a derp :p
