### ISSUE TITLE
Windows Cannot Find DayZ_x64 in the Batch File!

### ISSUE THREAD

**Issue by DD1505** [Arkensor/DayZCommunityOfflineMode#180]
When launching the batch file for DayZ_x64 it states that windows cannot find the executable. I know there is already an offline mission for DayZ however I'd like to get used to the firearms and towns of Chernarus (the map). I don't think the new mission already in the game has cheats like this mission does and that's why I'm looking for assistance in launching this mission. Cheers in advance!

**Comment by Arkensor** [comment]
Make sure not to launch the batch file as admin. Also if that does not work, you can use the mission parameter in the DayZ launcher to play the mission

**Comment by YozzaDayz** [comment]
Since upgrading to win10 im having this issue aswell worked not probs on win7 :(

**Comment by YozzaDayz** [comment]
![error](https://user-images.githubusercontent.com/53330670/62352663-9d962100-b500-11e9-807a-bcb2f3a45886.PNG)

**Comment by DD1505** [comment]
I don’t quite remember but I managed to launch it from the DayZ launcher. I’m afraid I can’t help you as I’m out of the house for a while. Sorry..

**Comment by YozzaDayz** [comment]
> I don’t quite remember but I managed to launch it from the DayZ launcher. I’m afraid I can’t help you as I’m out of the house for a while. Sorry..

dude any help would be great no rush whenever you get time to check thanks alot bro

**Comment by YozzaDayz** [comment]
Any joy dude?

**Comment by DD1505** [comment]
You need to place the actual mission file from your downloads into the DayZ missions folder in Steam, Steamapps, Common, DayZ. Drag/Drop you new mission into the Missions folder. Go into the Offline mission that you just placed and go to the folder that says Missions. Copy and paste the folder inside there into you DayZ missions folder from before (notice that the folder does not say master but instead goes on with Chernarus etc). Then if you go into the paramaters tab in the launcher for DayZ. You can find under the Advanced section there should be a Mission section. If you click the the 3 dots next to the box and navigate your drive (C or D etc.) to: Steam, Steamapps, Common, DayZ, Missions, then select the mission folder that does not say master on it. It should load the mission into the game. Then launch like normal.

I have made this extra detailed so others can underatand. 
Sorry for the delay. A bit busy with tests and ‘stuff’.

**Comment by YozzaDayz** [comment]
Legend thanks bro awesome

**Comment by DD1505** [comment]
> Legend thanks bro awesome

No Problem man let me know of any other issues!
