### ISSUE TITLE
Cannot compile world module.

### ISSUE THREAD

**Issue by xythol11** [Arkensor/DayZCommunityOfflineMode#181]
I tried everything. I am on the latest version. I am not on stress test branch. I verified game files. What do I do?
![Capture](https://user-images.githubusercontent.com/53451653/62084766-e99a4a80-b20e-11e9-8aa5-87011ec1c294.PNG)

**Comment by K3VLaR86** [comment]
did you use any mods when u saved your last build? if so check that you have the same mods active when opening a saved build
