### ISSUE TITLE
DayZCommunityOfflineMode

### ISSUE THREAD

**Issue by cizmi3** [Arkensor/DayZCommunityOfflineMode#182]
i need help for this!! 
![image](https://user-images.githubusercontent.com/53662125/62415919-324c6c00-b632-11e9-89e1-c551a522d1ee.png)
 
cannot load game dayz standalone

**Comment by neil501** [comment]
I had the same problem i had to use an older DayZCommunityOfflineMode version the one that worked for me was called EMU/DayZCommunityOfflineMode
Good luck!
