### ISSUE TITLE
How to load up a file

### ISSUE THREAD

**Issue by NecrolydeTV** [Arkensor/DayZCommunityOfflineMode#183]
Heya. Im building a massive bridge for my server on Dayz and sometimes the game crashes (even if i click 'Save' Button and 'export' 5minutes prior, reopening the bat file to contineu edditing all my buildings disapeared.

Is there a way that when i copy the spawnobject blablabla i get on a notepad and load it up on your bat.file ? If so could you tell me in detail how? im new to this. So i could contineu editing my bridges and add on to them before i upload it to the server.

**Comment by K3VLaR86** [comment]
Export the code ingame, then go to this folder
SteamLibrary\steamapps\common\DayZ\Missions\DayZCommunityOfflineMode.ChernarusPlus\core\modules\ComEditor
In this folder open the Comeditor.c
from here it shows u where to put the extracted code. Make sure u only put the object code in that looks like this
SpawnObject( "bldr_Platform1_Block", "7894.234375 202.000000 4516.959961", "24.000019 0.000000 0.000000" );
SpawnObject( "bldr_Platform1_Block", "7903.350586 202.000000 4512.926758", "24.000000 0.000000 0.000000" );
SpawnObject( "bldr_Platform1_Block", "7898.336914 202.000000 4526.081543", "24.000000 0.000000 0.000000" );

now save the file and start dayz.

**Comment by NecrolydeTV** [comment]
Cool,  and to import a map? for example Deer isle?

**Comment by K3VLaR86** [comment]
im also looking for that, found it a few days ago but forgot where

**Comment by NecrolydeTV** [comment]
Dam ok if you figure out please do tell me its for my second server that runs a different map

**Comment by Arkensor** [comment]
What do you mean with import a map?

**Comment by NecrolydeTV** [comment]
For example use deerisle instead of chernarus

**Comment by Arkensor** [comment]
You just need to rename / copy the mission folder and replace ChernarusPlus in the folder name with the map you want to start.
