### ISSUE TITLE
Static items 

### ISSUE THREAD

**Issue by frozendark01** [Arkensor/DayZCommunityOfflineMode#184]
Hi , 
Just install COM and it seems i cannot find in search Static items like roads, railway... etc.
ex: static_hbarrier, static_misc_bagfence, static_roadblock_bags, static_misc_barbedwire, static_rail_tracke, static _pier.. in Object Info i see the name but on Item and objects i cannot find them.

Thank you

**Comment by K3VLaR86** [comment]
for roads search for rds
for railway search rail or train, its easy to find
if all not works just hit buildings and scroll down the list
