### ISSUE TITLE
How to run Deer Isle mod

### ISSUE THREAD

**Issue by yohn7** [Arkensor/DayZCommunityOfflineMode#185]
I'm struggling to load the deer isle mod. I've tried editing the .bat file to include this parameter:

-mod=F:\PathToDeerIsleModDirectory

I've also tried adding launch parameters, and loading the mod in the standalone official launcher but everytime it just loads Chernarus.

**Comment by Arkensor** [comment]
Hi, you need to adjust the map name of the mission. if it is xxx.ChernaursPlus it will load chernarus.

**Comment by yohn7** [comment]
I'm unsure of what you mean sorry. Where do I adjust the map name? Do I edit the .bat file?
