### ISSUE TITLE
Missing Objects?...

### ISSUE THREAD

**Issue by Xapurass** [Arkensor/DayZCommunityOfflineMode#186]
It looks like the list of spawnable items is missing allot of standard world objects (e.g. slabs, piers, bridges).  Is there a reason for this?  Or is the list simply limited?

Also, not all lists are sorted (e.g. teleport locations).  Please correct this ;)

**Comment by K3VLaR86** [comment]
Check steam workshop -> Builder items, it adds almost every object in the game to the offline mode
