### ISSUE TITLE
still working for 1.05 ?

### ISSUE THREAD

**Issue by KAPTIC** [Arkensor/DayZCommunityOfflineMode#189]
The DayZCommunityOfflineMode is not working anymore after the patch... :/

**Comment by lonewolfss** [comment]
not working for me just throws errors at me since 1.05 updated today

**Comment by KAPTIC** [comment]
I don´t get a Errormessage but my Game crashes in the loading screen.. :(

**Comment by lonewolfss** [comment]
it may be a thing where you have to much loading in im not to sure im just testing this out now

**Comment by KAPTIC** [comment]
i reinstalled everything and it didn`t work

**Comment by phatbank** [comment]
As of 9/13, i presume after the Community Online Tool's update I get error trying to enter Offline Tool

Cant compile mission init script

![COT ERROR](https://user-images.githubusercontent.com/17785066/64910366-8d6a8780-d6e3-11e9-81f5-cf0e2751244d.PNG)

**Comment by neil501** [comment]
i had the same issue i had to uise the older version of DayZCommunityOfflineMode
 the file is called EMU/DayZCommunityOfflineMode
works perfect or just change the cameratool file! with the one from emu to get it to work!
