### ISSUE TITLE
Zoom in while sprinting?

### ISSUE THREAD

**Issue by krakenkoin** [Arkensor/DayZCommunityOfflineMode#19]
I noticed that you can no longer zoom in while sprinting. but I found a way to do it. So is there a way you can take advantage of it? When you are zooming in and quickly tap Sprint as you release middle mouse button you will Sprint while stuck in zoom mode. So is there a way to bind to a single key? 

(Edit : so it allows to zoom in while sprinting without my method? I know it's more of the developers issue but hoping for a temp fix)

Dunno if it's relevant to what's going on here but I do have everything running fine awesome work with this, can't wait for more updates!

**Comment by neonoxd** [comment]
That should probably be reported to the official dayz feedback tracker

**Comment by Arkensor** [comment]
@krakenkoin 
yes please report that. I noticed this too. When using the new v1.7 autosprint you can zoom in though, so they might be something wrong in their official sprint handler.

**Comment by krakenkoin** [comment]
Ok thanks guys, and I'll give autosprint a try.

**Comment by krakenkoin** [comment]
So I tried a different offline mission and I can zoom in while sprinting without auto sprint so maybe it's broken code arkensor?
