### ISSUE TITLE
Adding custom objects to spawn

### ISSUE THREAD

**Issue by Liriconst** [Arkensor/DayZCommunityOfflineMode#191]
Hello! First of all, I wanted to say thank you for your work!
I came across such a question. I made a model of the building. How can I add it to the list of objects for spawn? I did not find the answer to this question.
Thank you in advance!

**Comment by neil501** [comment]
does anyone know how to spawn items in offline mode?

**Comment by neil501** [comment]
nevermind i figured it out

**Comment by neil501** [comment]
now if i can get more then just the old hatchback to work!
