### ISSUE TITLE
How to add buildings from mods?

### ISSUE THREAD

**Issue by Liriconst** [Arkensor/DayZCommunityOfflineMode#193]
Friends! Please tell me how to connect mods to this tool?
How to add new buildings to the spawn menu?
For example, I made a new model of a house. I want to add it to the card. How do I connect it to this tool?
I really hope for your help!

**Comment by gofireup** [comment]
Start this tool by in your launcher (by choosing the path to the folder - offline tool). Then choose those mods, that you want to use and press play. If you build for your server, make sure all mods that you used installed on your server as well, not just with this tool or you will experience missing textures and even it may lead to crashes.
