### ISSUE TITLE
Can't compile mission init script

### ISSUE THREAD

**Issue by HansMadani** [Arkensor/DayZCommunityOfflineMode#195]
i tried to install this mod ver 1.01 on my Dayz1.015
on error message written "incompatible parameter UAAimleft.

**Comment by ihr-it-projekt** [comment]
i have this error message:

Can't compile mission init script'!

$CurrentDir:missions//DayZCommunityOfflineMode.ChernarusPlus//core//modules//ComEditor//gui//GameMenu.c(1): Multiple declaration of class 'GameMenu'

**Comment by neil501** [comment]
I had to use an older version called EMU/DayZCommunityOfflineMode for it to work! Maybe you do too?
