### ISSUE TITLE
No insert button!

### ISSUE THREAD

**Issue by gofireup** [Arkensor/DayZCommunityOfflineMode#199]
Hi! I need an advice. I do not have insert button on my laptop. It is like an function on another button and no matter what I do I can't open free camera. Any advice? Or may be you can just make this configurable please. I had same problem with Online Tools and I had to change the button to use free camera. Would you please kindly let us make a choice in buttons with Offlite Tools as well. Thank you in advance!

**Comment by theFoxzTrot** [comment]
Toggle your tools an enable free cam from there
