### ISSUE TITLE
Arkensor/DayZCommunityOfflineMode doesnt work for me!

### ISSUE THREAD

**Issue by neil501** [Arkensor/DayZCommunityOfflineMode#203]
I get too many errors trying to use this so i downloaded an older copy called EMU/DayZCommunityOfflineMode. Arkensor/DayZCommunityOfflineMode is for the 3.0 offline mode and EMU is older and it's for the 2.2 the problem i have in using the older version is i can only spawn the old hatchback and i can build the vs3 truck that's it! What i tried to do to get more cars to spawn is use your files in ARKENSOR is copy the DayZCommunityOfflineMode.ChernarusPlus\core\modules\ComEditor\gui\gameMenu c. file  when i started the game and tried to spawn the vehicles i was surprised to see the other s cars being offered in the spawn as they werent there before i changed the file but when i tried to use the sedan car the game just crashed.Can you please tell me what files i need to change to get the sedan and Sarka to spawn so i can use them? Please? i'll wait to hear what files need changing again if i try to just use the entire arkensor file i get errors and nothing works for me so i'm, trying to fix this or make a work around for this problem but i need your help thanks in advance, Matrix501 :)

**Comment by neil501** [comment]
Ok looks like i got your file zeroed to two files that dont work i have to use the older file to get the one vehicle to spawn which is the old hatchback! The others show up but if i try to hit execute with the sedan the game crashes and thew other two the gurpa and the new one sharpa i click them and nothing happens! How can i add vehicles to play offline?

**Comment by neil501** [comment]
I dont understand why i can only spawn the old hatchback is it because im using dayz version 1.0.15000??

**Comment by vanishare** [comment]
yes, it's because you have old and pirated version

**Comment by neil501** [comment]
why are you reading old posts? I fixed this problem 3 months ago! LOL! Your partly correct i never updated my version. and the file wasn't in the right folder.But thanks for the reply! :)
