### ISSUE TITLE
How to make it work with Livonia on Exp ?

### ISSUE THREAD

**Issue by vecuccio** [Arkensor/DayZCommunityOfflineMode#205]
I've seen Youtubers use it, so it must be possible.
I follwed the generiv Chernarus instructions and with the BAT file it says it can't find a running in stance of Steam, or if I run the BAT as Admin then it says that it can't find Dayz_x64.exe.

If I run the game with the parameter pasted into the game command line, then the DayZ loading bar will get stuck at around 25% and I have to exit out.

What's the trick to making it work with Livonia on experimental ?

**Comment by davidp234** [comment]
what you need to do is make a new folder called black.Enoch and copy everything from the default mission 

leave the default mission in there aswell 
then change the paramater for mission to the new enoch one

**Comment by vecuccio** [comment]
Thanks for your reply and instructions. I gave them a try. 

However, my BLISS addons folder is empty, and I don't have folder called DayzOffline.ChernarusPlus (I have the other 2 (one of which is the renamed copy of the original as per your instructions))

I went ahead anyway, and DayZ crashed at the end of the loading bar with an Access Violation 0xC00000005. So I guess it either needs those BLISS/Addons files, or the missing folder stuff ?

Do you know where I can get either or both ?

**Comment by vecuccio** [comment]
I took a copy of the dayzOffline.ChernarusPlus from normal DayZ and pasted it across to give me the 3 folders in your screenshot. It still crashed in the same manner.

I did notice a Reddit thread about this, and one person said that you have to go through every text file and replace the world ChernarusPlus with Enoch, which makes sense, but i'm hoping it's not true.

**Comment by LRP85** [comment]
https://www.youtube.com/watch?v=qqP09XlbINM&t=85s

**Comment by LRP85** [comment]
[https://www.youtube.com/watch?v=qqP09XlbINM&t=85s](url)
