### ISSUE TITLE
Livonia Offline no sound

### ISSUE THREAD

**Issue by LRP85** [Arkensor/DayZCommunityOfflineMode#206]
Hi there! Just duplicated and changed the DayZCommunityOfflineMode.ChernarusPlus folder and every file inside to "enoch". I enter the game and everything seems good but I dont get sound on the game! And also theres no loot! In Chernarus offline everything works fine! Did i miss something?

**Comment by Arkensor** [comment]
The spawn positions must be adjusted. I will look into a Livonia soon

**Comment by Rochambeau** [comment]
I'm still suffering with this issue, too. Despite random spawning, it's almost always outside the Livonia map boundaries and results in the loss of sound in-game. Renaming the folder and a .bat file from DayZCommunityOfflineMode.ChernarusPlus to DayZCommunityOfflineMode.Enoch doesn't solve the issue, either.
