### ISSUE TITLE
Livonia Edition now Available for Download

### ISSUE THREAD

**Issue by CypherMediaGIT** [Arkensor/DayZCommunityOfflineMode#208]
This is a fork and update of DayZCommunityOfflineMode to work with Livonia Map,
You must have Livonia Map paid for and downloaded and installed for this mod to work, this mod does not provide any links or the game files for Livonia.

https://github.com/CypherMediaGIT/DayZCommunityOfflineMode-Livonia-Edition

**Comment by SAYREXx** [comment]
Hi! Please help me with this: https://github.com/Arkensor/DayZCommunityOfflineMode/issues/213
