### ISSUE TITLE
Turn off infinite ammo

### ISSUE THREAD

**Issue by CaptainDucko** [Arkensor/DayZCommunityOfflineMode#209]
Is there a way to turn off infinite ammo? I'm quite new to day z and want an offline mod like this so I can work out how to deal with Day Z's finicky reload system...if there ammo is just inifite this completely prevents it from being useful for me.

**Comment by Arkensor** [comment]
If you want to play offline without any admin tools use the launcher and select the dayzOffline.Chernarusplus folder for the mission parameter.
