### ISSUE TITLE
Cant compile (Compile error  Can´t comile missions init script`!)

### ISSUE THREAD

**Issue by Asmond** [Arkensor/DayZCommunityOfflineMode#21]
**Problem:**

- I follow the instructions, copy the Missions folder and run the game from the "Reset Hive and play" file
- The game starts but the following error show up (https://i.imgur.com/i4okSRQ.png)
- The screen do not move foward of a light blue background where you can access the menu (continue, reset, options, but if you press reset, the Dayz logo shows up and never start the game).
- The error window keep poping up
- Never had this problem with the previous patch._

**Thx!**

**Comment by Arkensor** [comment]
Hey there,

try to delete the Missions folder and validate the game. Then download the latest release and try it again

**Comment by Asmond** [comment]
_Fixed._

_Thx dude._
