### ISSUE TITLE
Is persistance possible?

### ISSUE THREAD

**Issue by jessejaymz08** [Arkensor/DayZCommunityOfflineMode#210]
I was wondering if there is a way for me to save my progress and character etc, like enabling persistance or however it works. i apologize if this issue has already been covered, im quite new to this and only started using it today, i tried to look around for an answer but just got confused. Also if it  possible atm can someone explain how to do it like how to load up the previous game i played. Any help is appreciated, thanks

**Comment by Arkensor** [comment]
I am thinking about adding this in a future rewrite. Right now the persistence is not maintained anymore, so it's not likely there will be anything in that regard before the rewrite.
