### ISSUE TITLE
Game Crash after selected some firearms

### ISSUE THREAD

**Issue by PR9INICHEK** [Arkensor/DayZCommunityOfflineMode#211]
Try to get above firearms

Objects -> Firearms:
GP25Base
GP25
GP25Standalone

M203Base
M203
M203Standalone

Magnum
Red9

**Comment by Lex7K** [comment]
It also resets the game process on the system, when the choice to Winchester 70, Gren and izh45Shotgun

**Comment by TyphoonZR** [comment]
Since the update few things have become broken and crash one the weapons and 2 the wolves and bears AI that are spawned no longer attacks zombies nor do they attack them I hope they fix this I enjoy the single player

**Comment by Arkensor** [comment]
Resolved in latest version

**Comment by Lex7K** [comment]
> 
> 
> Resolved in latest version

Now I get a game crash when I select the first two items in the Firearms list - PVCBoW and QuickieBow
