### ISSUE TITLE
GetCEApi() Livonia

### ISSUE THREAD

**Issue by SAYREXx** [Arkensor/DayZCommunityOfflineMode#213]
Hello! Please tell me, do I also need to use these coordinates for the livonia map?
`GetCEApi().ExportProxyData( "7500 0 7500", 10000 );`

**Comment by CypherMediaGIT** [comment]
No this is only if you want to create the file for loot, animals and zombie spawns

**Comment by SAYREXx** [comment]
> No this is only if you want to create the file for loot, animals and zombie spawns it can be used on both maps

Yes, that's exactly what I want to do. But I don’t know what sizes to indicate for the livonia card

**Comment by Arkensor** [comment]
It should work fine when you choose "0 0 0", 100000. Try that
