### ISSUE TITLE
DayZ crashes everytime I scroll on the weapons tab in offline mode

### ISSUE THREAD

**Issue by yoshi7827** [Arkensor/DayZCommunityOfflineMode#226]
Basically i spawn in and i try to grab a weapon rather spawn one in scroll on the ui and it crashes
Not sure exactly what the problem is I have 16gb of ram a 4 core cpu and a gtx 1660 so i think im fine with running things I think it might just be a file integrity thing if i could get some help that would be fantastic

**Comment by I3uryme** [comment]
I have this same issue, is there a fix?
