### ISSUE TITLE
Cannot find Dayz_64.exe

### ISSUE THREAD

**Issue by oz19821** [Arkensor/DayZCommunityOfflineMode#227]
Hello does anyone know if this still works? 
Im getting the error in the title.

**Comment by RumpeIstiltskin** [comment]
It still works. Where are you putting the Missions folder?

**Comment by oz19821** [comment]
Common/Dayz/Missions 
When i had this installed before my Dayz may have been on a drive that i no longer have its nowon C instead of D could that effect it?

**Comment by fariegn** [comment]
> Hello does anyone know if this still works?
> Im getting the error in the title.

Hi, I just figured out the issue. The bat file is looking for DayZ_64.exe in the wrong directory. 

Edit the bat file and change 
`cd ../ ../`

with

`cd ../..`
