### ISSUE TITLE
Cannot compile mission init script'!

### ISSUE THREAD

**Issue by Everythingelse3six5** [Arkensor/DayZCommunityOfflineMode#228]
Hello! Everytime I run the DayZCommunityOfflineMode.bat it starts up but after a minute it freezes on the loading page and spits out this error:

![Compile Error](https://user-images.githubusercontent.com/66157047/83321816-10068900-a218-11ea-9beb-ed2d260c3d15.png)

If you have any suggestions or ideas please let me know! I've already tried deleting my xml files in documents which didn't do anything.

**Comment by DinkleThings** [comment]
Dayz has changed some background things with 'GET' calls. They now need to be prefixed with 'COM_'

You can test the new branch at - https://github.com/Arkensor/DayZCommunityOfflineMode/tree/development

Be advised that this branch may experience issues. Please swap to the master branch once they are merged.
