### ISSUE TITLE
Can't Complete Mission Init Script 

### ISSUE THREAD

**Issue by SkeletonJ** [Arkensor/DayZCommunityOfflineMode#229]
![script error](https://user-images.githubusercontent.com/66319231/83533190-25650700-a4e7-11ea-9c15-bedca55ec686.png)

litarraly have tried deleting , then redownloading , everything was working yesterday fine stopped working on a build to jump on a dayz server to do some admin duties come back to offline and this is the error i am getting , 

have deleted dayz , and all files and re installed everything and still get this error

**Comment by broman** [comment]
Can repro this issue, mods loaded:
```
1559212036 # Community Framework
1849039435 # BaseFortifications
1565871491 # BuilderItems
1869021368 # [CrSk] BMW 525i E34
1815655441 # CJ187-Cars
1819514788 # EarPlugs
1895398348 # Kamaz_Truck
1566911166 # Mass'sManyItemOverhaul
2007175894 # MoreDoors
1665663702 # MoreGuns
1999076953 # Notes
1617874376 # OP_BaseItems
1644467354 # Summer_Chernarus
1583941197 # SQUAD MSF-C
1797720064 # WindstrideClothing
1962579662 # Mercedes_G65_AMG
1856309515 # (WIP) TrailBrozer SUV
2095424002 # M1161 Growler ITV
```

**Comment by lonewolfss** [comment]
any fix yet guys?

**Comment by DinkleThings** [comment]
Dayz has changed some background things with 'GET' calls. They now need to be prefixed with 'COM_'

You can test the new branch at - https://github.com/Arkensor/DayZCommunityOfflineMode/tree/development

Be advised that this branch may experience issues. Please swap to the master branch once they are merged.

@broman

**Comment by broman** [comment]
@DinkleThings thank you! Confirm fixed as of develop branch.

**Comment by DinkleThings** [comment]
> @DinkleThings thank you! Confirm fixed as of develop branch.

Though....the camera gets a bit wonky and wont TP you properly. No doubt it will be fixed soon however.

**Comment by broman** [comment]
Yeah, there's a few issues but it is of course to be expected on develop
