### ISSUE TITLE
cant compile mission init script';

### ISSUE THREAD

**Issue by davidp234** [Arkensor/DayZCommunityOfflineMode#231]
https://prnt.sc/stwxz0

**Comment by DinkleThings** [comment]
Dayz has changed some background things with 'GET' calls. They now need to be prefixed with 'COM_'

You can test the new branch at - https://github.com/Arkensor/DayZCommunityOfflineMode/tree/development

Be advised that this branch may experience issues. Please swap to the master branch once they are merged.
