### ISSUE TITLE
Incompatibility with DayZ Expansion

### ISSUE THREAD

**Issue by irvnriir** [Arkensor/DayZCommunityOfflineMode#232]
I merged COM with `@DayZ-Expansion\Missions\Expansion.ChernarusPlusGloom` , and launched with required mods . But i received this:
![Screenshot 06-05-2020 19 10 08](https://user-images.githubusercontent.com/13949704/83898891-379daa00-a760-11ea-9d21-d9e22f733771.png)

"Ignore"-ing it -- worked, but still .

DayZ Expansion has separate "COM" mission X) .

**Comment by neil501** [comment]
I think what needs to happen is they have to write another offline program for the expansion like they did with livonia.

**Comment by irvnriir** [comment]
While Expan. has own COM its ok, just it should be warned near/at top of the readme .

**Comment by neil501** [comment]
i cant get dayz expansion or deer isle to work! The livonia map always comes up blank! Playing offline i can only play the original map and that's it! no updated vehicles only the 4 original vehicles and weapons. I really wish they would write a new program for these updates. Playing the original offline gets boring after a while especially playing online all the new things dayz has added. I wish we could also play offline with all the new things too bad! But i have hope they will write and update this to include the new maps and updates!
