### ISSUE TITLE
Ambiguous function call 'GetModuleManager'

### ISSUE THREAD

**Issue by Caetano-Lopes** [Arkensor/DayZCommunityOfflineMode#234]
![image](https://user-images.githubusercontent.com/55096198/84061193-61034380-a9b5-11ea-9a7c-29e4b4862b62.png)
When i try to start the game in offline mode with the addons (CF, VPPAdminTools, VPPNotifications) this error happens ☝️

**Comment by DinkleThings** [comment]
Dayz has changed some background things with 'GET' calls. They now need to be prefixed with 'COM_'

You can test the new branch at - https://discordapp.com/channels/467261322120396831/491178137728843777/721287469936541807

Be advised that this branch may experience issues. Please swap to the master branch once they are merged.
