### ISSUE TITLE
Since Dayz with all the updates Offline Mode NO LONGER WORKS!

### ISSUE THREAD

**Issue by neil501** [Arkensor/DayZCommunityOfflineMode#235]
Hi Arkensor,

 I'm not sure what is going but since dayz rolled out the last update i can no longer play offline when i click on the game starts and i wind up on the dayz multiplayer start page as if i started the game regular even though i did change the start ini page files to read online: false and i changed the other one too so the game know to play offline but why is it failing now??? Can you help please? Update so far since writing this i have been able to get version 1.05 to work offline but that is it! and no help from anyone explaining how they got offline to work. almost a week now trying to get this to work! Please anyone help!

**Comment by lonewolfss** [comment]
same here just throws a error dosent matter if i click ignore it still wont load!

**Comment by DanielAStocker** [comment]
How can I play 1.08 in offline mod?

**Comment by neil501** [comment]
Well i'm glad to know i'm not the only one with this issue so it's not my computer then it's the program! The odd thing about this issue is i have kept almost every dayz version on an external harddrive and no matter what version i use they all dont work anymore and before they all worked i have the org 1.01 where you can drink any water and wont get sick but only one car is working the hatchback then i have the 1.05 version where all 4 cars were added and i have 1.06 and 1.07 each one brings something different but sadly this last update something killed playing the offline mode it used to run so fast and smooth now nothing! i really hope they can fix this issue offline to me is the best! especially being able to add a car when your sick of walking!

**Comment by DanielAStocker** [comment]
hey i solved it, i can now play chernarus and livonia offline (editor) at 1.07 and chernarus at 1.08

**Comment by DinkleThings** [comment]
Dayz has changed some background things with 'GET' calls. They now need to be prefixed with 'COM_'

You can test the new branch at - https://discordapp.com/channels/467261322120396831/491178137728843777/721287469936541807

Be advised that this branch may experience issues. Please swap to the master branch once they are merged.

**Comment by neil501** [comment]
> hey i solved it, i can now play chernarus and livonia offline (editor) at 1.07 and chernarus at 1.08

Hey! congrats on being able to play offline! Can you please explain exactly what you did so others can learn how to play offline?

**Comment by neil501** [comment]
hi dinkle that link you posted takes you to the 1.02 old version of Arkensor DayZ CommunityOfflineMode files! The rest i have no idea what your talking about with"Get" calls and having to prefix with "COM"  Can you show an example or explain what you did or how you were able to play offline? As far as most of us dayz offline STILL DOESN'T WORK!

**Comment by neil501** [comment]
well these guys just gave me an idea i'll try to use the older versions of dayzcommunityOfflineMode files maybe one of the old ones can get the new updates to work? I'll keep everyone posted and if it works i'll explain EVERYTHING! So there is no confusion and everyone will be able to play offline! No mind-reading needed here! LOL!!!!

**Comment by DinkleThings** [comment]
@neil501 

Its not 'old 1.02'. The current live branch also uses the same 1.02 Bat file.

If you have a look at the side by view of the recent changes made to the Dev branch of the Offline Mod, you will find your answer. A quick example of when you load the mod and Dayz. The unbolded Text is the old call. The bolded text are the new calls.

        GetModuleManager().OnInit();
		GetModuleManager().OnMissionStart();
        **COM_GetModuleManager().OnInit();
		COM_GetModuleManager().OnMissionStart();**

I can confirm the Dev branch will launch, however it has some small issues.

Why they have added 'COM_' to every get call? I am not too sure. I cannot find any documention from Bohemia on this or anything from @Arkensor himself :(

**Comment by DanielAStocker** [comment]
@neil501 
I have a YouTube channel Daniel A.Stocker or add me on Steam Daniel Stocker |YouTube. Com , then i can say if you can Play 1.08 Offline, And make cool YouTube content, 
Its not easy , i work 1 long day top find this out🤯

**Comment by neil501** [comment]
Thank you dinkle i checked all my files and looks like i already have the COM added to all the correct files but OFFLINE STILL DO NOT WORK! The best i've been able to do is to play the older version 1.05 on one of my external harddrive's From what i have seen it should work but it just doesnt!

**Comment by neil501** [comment]
well i tried the so called new one but it does nothing! well the best i was able to do was to go find all the old files to get the 1.05 version to work offline but after that i don't know what happened Offline version just stops working period! For a short time the 1.07 did work but nothing could spawn it worked but it was broken! So like i said before after the last update what ever was done killed the offline version! not just me but most cant play offline so i hope with the new expansion i really hope they can get the expansion to work.

**Comment by neil501** [comment]
> Daniel A.Stocker

hi daniel! well what ive found there are quite a lot of Daniel Stocker's on youtube! but not one Daniel A. Stocker! I wanted to know did you make a video of what you did to get offline to work?

**Comment by neil501** [comment]
tommorow i'm updating from dayz 1.08 experimental to dayz 1.08 stable. ive spent well over a month trying and i FINALLY got the original Chenarus map for version 1.7.153006 to work! FINALLY!!! it doesnt have any modded vehicles nothing fancy jst basic game but i'm very very happy it works! I hope i can just follow thru with vesion 1.08 tommorow but i cant get deer isle the new expansion or even livonia to work so i hope it can be fixed. but i'm contecnt just to play offline current version right now it's no different than version 1.05! really!

**Comment by neil501** [comment]
I was able to getversion 1.7.1 to play offline!
