### ISSUE TITLE
1.08 Offline Creator Mod

### ISSUE THREAD

**Issue by DanielAStocker** [Arkensor/DayZCommunityOfflineMode#236]
I download the Chernarus Offline Map. This is 1.07

How can I play the 1.08 in offline mod?

Thx

**Comment by DinkleThings** [comment]
Dayz has changed some background things with 'GET' calls. They now need to be prefixed with 'COM_'

You can test the new branch at - https://discordapp.com/channels/467261322120396831/491178137728843777/721287469936541807

Be advised that this branch may experience issues. Please swap to the master branch once they are merged.

**Comment by nvrsbr** [comment]
https://i.postimg.cc/6QqjwhND/Error.jpg

**Comment by DinkleThings** [comment]
> https://i.postimg.cc/6QqjwhND/Error.jpg

Have you tried the dev branch.....

**Comment by nvrsbr** [comment]
> > https://i.postimg.cc/6QqjwhND/Error.jpg
> 
> Have you tried the dev branch.....

Yes.
