### ISSUE TITLE
Nothing Works on Experimental Version

### ISSUE THREAD

**Issue by MrSmallZzy** [Arkensor/DayZCommunityOfflineMode#238]
I can not teleport, spawn items in and change camera back to player, it freezes when changing back camera to player.

**Comment by EL-Kontractor** [comment]
same for me

**Comment by DinkleThings** [comment]
Its experimental, nothing is expected to work %100

They will hopefully be solving the issues soemwhere down the road

**Comment by neil501** [comment]
I would think he has to write a new program for expansion just like he did for livonia since so many things are changed in expansion I really hope he gets around to doing this as i love expansion especially with the boats and planes and new vehicles!

**Comment by MrSmallZzy** [comment]
> I would think he has to write a new program for expansion just like he did for livonia since so many things are changed in expansion I really hope he gets around to doing this as i love expansion especially with the boats and planes and new vehicles!

Its not for expansion, its the regular game that nothing works on. Tried to start up DayZ 1.07 and it threw an error & wouldn't load and was recommended to use the experimental version and it doesn't work at all. Its currently just a lead weight.

**Comment by neil501** [comment]
Agreed! thats why i started this link i was hoping to at least get some kind of chat going with the makers of the ones who actually made the offline mode. They obviously know what they are doing and if they could make something like this,Then i can't see why they couldn't easily explain how we could get the offline mode to work! Please dont feel bad most people can't play offline, People i talk to online tell me they tried it and it didn't work and most went right back to playing online so we are the majority so i would think after the game is more stable they will write a whole new program to fix everything like they did before. It's the waiting that sucks!

**Comment by Polosolo12** [comment]
None of the cheats work for me at all. This is my first time trying this mod though, so I may be doing something wrong. Can I still get it to work on earlier versions you think?

**Comment by MJRamon** [comment]
I second that. Cannot teleport to cursor, cannot spawn items at cursor or on ground, items can be spawned to inventory, but not 100%, sometimes they skip. Pressing Insert teleports camera somewhere to the ocean and you can't get back to character.

**Comment by neil501** [comment]
i can ONLY use the offline mode in older versions! Even then some of the guns dont work! well they never worked like the 429 machine gun the scout, the grenade launcher that goes with the m16 those guns have been dead since the very 1st version but i'm happy just to be able to play and spawn things in offline mode!
