### ISSUE TITLE
Free Camera Zoom Function

### ISSUE THREAD

**Issue by DoctorDeSync** [Arkensor/DayZCommunityOfflineMode#24]
Possibility for a Free Cam zoom function.

For standard zoom (1pp/3pp zoom): Middle Mouse Button while in free cam mode

For manipulating fov: PageUp/PageDown

**Comment by krakenkoin** [comment]
Would be awesome for zombie placement with O spawn when filling a city for a self made "mission"

**Comment by DannyDog** [comment]
Implemented in commit 50f94fcd008e02cfe953641fd25aa8fde10a0f1f
