### ISSUE TITLE
Mods not loading

### ISSUE THREAD

**Issue by TheWeedMan** [Arkensor/DayZCommunityOfflineMode#246]
Since 1.08 update I've been unable to load any mods via the DayZCommunityOfflineMode.bat file.
Below is the method I was using pre 1.08:-

**start DayZ_x64.exe -mission=.\Missions\DayZCommunityOfflineMode.ChernarusPlus -nosplash -noPause -noBenchmark -filePatching -doLogs -scriptDebug=true -mod=@BuilderItems;@BuilderStatics**

For some odd reason this fails to work now and the mods seem to be ignored. 
I've tried several variations of the mod command but nothing seems to pick up the mods.  Any ideas?

**Comment by EL-Kontractor** [comment]
try ... ?
-mod=!Workshop/@BuilderItems;!Workshop/BuilderStatics

**Comment by TheWeedMan** [comment]
EL-Kontractor my friend you are an absolute Legend, its now working using your command line.  You have no idea how frustrated I've been over the last week with that haha.

Very much appreciated bud ;)
