### ISSUE TITLE
Items quality

### ISSUE THREAD

**Issue by temakos90** [Arkensor/DayZCommunityOfflineMode#251]
Hello. Sorry for my English. I have some question. How i can change item quality whe i spawn them? All items is ruined.

**Comment by pvolchek** [comment]
Set State = 1000

**Comment by DaGreekGeek** [comment]
I dug around and fixed it on my end.  Open the mod files in a text editor:

".\Missions\DayZCommunityOfflineMode.ChernarusPlus\core\modules\ComEditor\gui\layouts\ObjectMenu.layout"

The default value under "EditBoxWidgetClass state_items"

Set 100 to 1000 and you'll never have to do that again. Same goes for any other settings you might think of but that requires more tinkering.
