### ISSUE TITLE
Can't compile mission init script'! 

### ISSUE THREAD

**Issue by RevengeTM** [Arkensor/DayZCommunityOfflineMode#259]
https://gyazo.com/97160dbb64a59507bc0ca80700429a2c

**Comment by kellixon** [comment]
Personally, I do not use what offline gives, but use my own Spawn helper function in init.c.
//Spawn helper function
	void SpawnObject(string objectName, vector position, vector orientation)
	{
		Object obj;
		obj = Object.Cast(GetGame().CreateObject(objectName, "0 0 0"));
		obj.SetPosition(position);
		obj.SetOrientation(orientation);

		// Force update collisions
		if (obj.CanAffectPathgraph())
		{
			obj.SetAffectPathgraph(true, false);
			GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(GetGame().UpdatePathgraphRegionByObject, 100, false, obj);
		}
	}
