### ISSUE TITLE
Sometimes the zombie and animal spawns get gitchy and spawn in a character in a hazmat suit with a gun.

### ISSUE THREAD

**Issue by twist2k** [Arkensor/DayZCommunityOfflineMode#26]
It is a strange bug and may have nothing to do with the custom script, but just wanted to mention it!

Thanks for the work and examples for the community!

**Comment by MrEmuu** [comment]
It sounds like conflicting scripts, are you using any other mods/scripts folders/.pbos? 

You should ONLY use the mission file, every other file in your DayZ should be vanilla.

**Comment by twist2k** [comment]
Not using anything else but Vanilla DayZ stress test build and your scripts. And it does not always happen, just sometimes it starts after messing about for a bit. But then the key binds will only spawn those guys, not animals or zombies. Have tried to find steps to reproduce and seems to be random at this point as far as I can tell.
