### ISSUE TITLE
why doesnt any of the offline mods include the new helicopters i cant spawn any in offline mode!

### ISSUE THREAD

**Issue by neil501** [Arkensor/DayZCommunityOfflineMode#264]
I wanted to know why none of the new vehicles and helicpters werent added to the offline mode? Ive tried to do this myself but i just dont have the skill to do something that advanced.I have spent a good month trying to spawn a heli in offline mode but i cant get it to work then i thought about why hasnt this ever been added?

**Comment by lasyen** [comment]
Are you thinking of Expansion mod? Helicopters aren't in the base game. Try Expansion's Discord to see if they can help you add Expansion's objects to the spawn list in COM.
