### ISSUE TITLE
Hi mate im having a lot of trouble getting this to work i would love to speak to you personally and get some help

### ISSUE THREAD

**Issue by DaMadesTx** [Arkensor/DayZCommunityOfflineMode#267]
I've tried all the methods under the sun to get my custom location spawning loot but nothing works 'ive spoken to numerus people asking and they haven't seemed to help me If you can please get in touch with me at daniel.smith1649@gmail.com or any other way you are happy with as i would love to get this working cheers

**Comment by johnstonecooper484** [comment]
ok some thing not rite i e mailed you and we decided in discord to talk but the link i got from you is for pokemon go? it's a bot called Dyno bot ? whats this about? if this is a mastack plz e mail me you dicord youser id ill masig you on that thank you if not f this

**Comment by DaMadesTx** [comment]
Wow bro I definitely did not sent you a link to pokemon go I needed help
with spawning loot on my custom area of the map and I actually figured the
issue and now can use it however I definitely didn’t sent you any bullshit
bro I’m not trying to f anyone’s computer up

**Comment by DaMadesTx** [comment]
https://discord.gg/KwArFT

This is my discord channel mate ^ should look good there
