### ISSUE TITLE
Namalsk

### ISSUE THREAD

**Issue by vecuccio** [Arkensor/DayZCommunityOfflineMode#274]
All you need to do is add DayZCommunityOfflineMode.Namalsk to the missions parameter in BIS launcher ?
When I did that the game crashes with access violations as it loads. Do I need to add something to the 'WORLD' option too ?

I noticed the Namalsk BAT file. I tried it (after changing the Steam paths to match my own) buy nothing happened.

**Comment by vecuccio** [comment]
Ah. Never mind. I went straight to the community bat file inside the namalsk folder instead. That worked.

Unfortunately there are no TP coordinates for Namalsk, only Chernarus. But at least it's working.

**Comment by Boogeyman10** [comment]
> Ah. Never mind. I went straight to the community bat file inside the namalsk folder instead. That worked.
> 
> Unfortunately there are no TP coordinates for Namalsk, only Chernarus. But at least it's working.

what to do asks to launch steam playing pirate?
