### ISSUE TITLE
Namalsk Offline Mode

### ISSUE THREAD

**Issue by SycoraxAriel** [Arkensor/DayZCommunityOfflineMode#277]
Hello there! I am trying to play Namalsk offline mode however it crashes as soon as I start it up. I have did exactly how the installation process went and it does not work even when I launch it through DayZCommunityOfflineMode.bat for Namalsk folder. Is there any fix to this?

Does this require me downloading the Namalsk addons?

**Comment by SycoraxAriel** [comment]
Nevermind! It is required to have mods installed.

**Comment by gruunt** [comment]
What addons are there? can you list them because I think I have them all but my game still crashes

**Comment by SycoraxAriel** [comment]
> What addons are there? can you list them because I think I have them all but my game still crashes

Hey man, the two addons I had was, Namalsk Survival, and Namalsk Island
