### ISSUE TITLE
Namalsk Offline Crashing

### ISSUE THREAD

**Issue by ZVOZ** [Arkensor/DayZCommunityOfflineMode#278]
The game boots up and starts to load, then crashes after a few seconds. At first, I realised the -mod parameter was pointing to the !Workshop folder in my DayZ directory, while my Namalsk files were located in \steamapps\workshop\content\...
I tried copying the mod files to the specified !Workshop folder, making a shortcut folder, of the same name, redirecting to the \steamapps\workshop folder, and changing the -mod parameter directly to the \steamapps\workshop folder. None of this has worked, and it crashes everytime.

I've also tried changing HIVE_ENABLED to false in the CommunityOfflineClient.c file, where the game does load but loads the Chernarus map instead.

The regular Chernarus Plus mode works just fine

**Comment by gruunt** [comment]
I'm having the exact same problem and I don't know why

**Comment by C013ain** [comment]
Same issue here, any solutions yet?

**Comment by Arkensor** [comment]
You need to be subscribed to the Namalsk workshop item and have launched the dayz launcher once to make sure the mod is properly installed. Then use the batch file that comes with the downloads

**Comment by gruunt** [comment]
> The game boots up and starts to load, then crashes after a few seconds. At first, I realised the -mod parameter was pointing to the !Workshop folder in my DayZ directory, while my Namalsk files were located in \steamapps\workshop\content...
> I tried copying the mod files to the specified !Workshop folder, making a shortcut folder, of the same name, redirecting to the \steamapps\workshop folder, and changing the -mod parameter directly to the \steamapps\workshop folder. None of this has worked, and it crashes everytime.
> 
> I've also tried changing HIVE_ENABLED to false in the CommunityOfflineClient.c file, where the game does load but loads the Chernarus map instead.
> 
> The regular Chernarus Plus mode works just fine

Did you ever get it to work because I haven't. I've played 12+ hours on Namalsk and the offline mode still doesnt work

**Comment by C013ain** [comment]
subscribed both to namalsk island and namalsk survival. playing on servers so mods must be fine, still crashes on startup

**Comment by C013ain** [comment]
[script_2020-12-13_10-36-43.log](https://github.com/Arkensor/DayZCommunityOfflineMode/files/5684477/script_2020-12-13_10-36-43.log)

**Comment by ZVOZ** [comment]
Follow Arkensors solution, you simply need to run the official DayZ launcher once, it will properly setup the workshop files. Then just run the game from the .bat file like normal.
