### ISSUE TITLE
Offline Namalsk being extremely laggy

### ISSUE THREAD

**Issue by SycoraxAriel** [Arkensor/DayZCommunityOfflineMode#279]
Hey yall! 

I recently tried out offline Namalsk and was excited until I ran into the issue with it being so laggy to the point where its unplayable. 

Does anyone know a fix to reduce the lag at all? 

I try the Chernarus one and its fine even when it had zombies in them. I'd love to know!

**Comment by Arkensor** [comment]
Not related to this offline mode. Try disable CE as described in the wiki
