### ISSUE TITLE
Issues while trying to reach namalsk

### ISSUE THREAD

**Issue by AdmiralManes** [Arkensor/DayZCommunityOfflineMode#281]
Hello, and thanks for this tool !

I was trying to get on Namalsk for editing some areas, but the game keeps crashing everytime I try to launch the Offlinemode.

Do you have any tips?

**Comment by Mochitok** [comment]
same problem

**Comment by Arkensor** [comment]
Try this: https://github.com/Arkensor/DayZCommunityOfflineMode/wiki/Toggle-loot-and-infected-spawn
