### ISSUE TITLE
Change base item spawn health.

### ISSUE THREAD

**Issue by Rayvex** [Arkensor/DayZCommunityOfflineMode#284]
I've been trying to change the health (or find out the file that changes it) for items spawned in through the ComEditor. The reason is I want to change it from 100 to 1000 as some/most items have a health value over 100. Take the barrel for example: When clicked without changing the base spawn health (100), the barrel spawns badly damaged. But when changing the value to 1000, it spawns pristine.

**Comment by Arkensor** [comment]
You will have to adjust that in the scripts. https://github.com/Arkensor/DayZCommunityOfflineMode/blob/master/Missions/DayZCommunityOfflineMode.ChernarusPlus/core/modules/ComEditor/gui/ObjectMenu.c#L106 follow that variable and adjust the code as needed.
