### ISSUE TITLE
base building

### ISSUE THREAD

**Issue by AndroDawton** [Arkensor/DayZCommunityOfflineMode#285]
Hi,
I just downloaded the latest DayZ experimental version and started the # DayZCommunityOfflineMode 3.6 with the bat file.

When I try to set up a structure with a kit, the animation just ends after the circle is closed.
 
https://i.imgur.com/GdxNj7a.jpg

https://i.imgur.com/HlneibP.jpg

So I cant build anything. What could I try to solve this?

**Comment by AlphaFr3d** [comment]
Hi I am also having this issue. I cannot place fence kits at all, is this something that can be corrected?
I love this everything that has been done on the Offline mode btw, great work!

**Comment by Arkensor** [comment]
I am not sure if and how this would be an issue with COM. I will have a look at it.

**Comment by TheFigBird** [comment]
I too am having the same issue though was previous able to get it to work - could it be the 1.11 update?

**Comment by bpNeinhorn** [comment]
Also affects placing of barrels and crates.
Garden plots can be made

**Comment by pvolchek** [comment]
Base building is an important part of an offline mode. I always use it to build some prototypes or try out things before starting them in a real server.
Currently, it looks like its broken (although worked fine in the previous version)

**Comment by AlphaFr3d** [comment]
Still not working, basically cannot place anything that needs to white outline placement function e.g. fence kits, mines, barrels etc.  its a real shame as I used to use Offline mode to make base designs before implementing into official mode.

**Comment by bpNeinhorn** [comment]
**Basebuilding is working again after the 1.12 update.**

**Comment by Arkensor** [comment]
> **Basebuilding is working again after the 1.12 update.**

Great.
