### ISSUE TITLE
why cant i spawn boats and heli's in this offline mode?

### ISSUE THREAD

**Issue by neil501** [Arkensor/DayZCommunityOfflineMode#286]
My friends tell me they can spawn boats and helicopters in their offline mode. What am i missing? great mod by the way you did a great job on this mod! it works great but it looks like nothing has changed since version 1.05 came out. Can you please help????

**Comment by Arkensor** [comment]
What seems to be different? There should be nothing stopping you from spawning them. Modded vehicles are not part of the curated menu and are instead only accessible via the object spawn menu.

**Comment by neil501** [comment]
But nothing shows up in the spawn menu only the original things that have been there since version 1.05! It's like nothing has changed in the offline mode! Like this mode DayZCommunityOfflineMode.ChernarusPlus this one works and i can spawn the 4 vehicles and other items but no aircraft and no boats! The ExpansionCOM NO! that one dont even work! It never has worked for me. Anyway i can just add like a single heli into DayZCommunityOfflineMode.ChernarusPlus file? When i play online i can fly and drive a boat no problem it's ONLY in offline mode that is the issue.

**Comment by neil501** [comment]
The ONLY thing that shows up in the object spawn menu is the same 4 original vehicles that have always been there and that is it!

**Comment by Arkensor** [comment]
> The ONLY thing that shows up in the object spawn menu is the same 4 original vehicles that have always been there and that is it!

That is because nothing else has been added. COM does not show anything Expansion related. That is why they have their own fork of this. Please ask them to fix their version if that does not work for you.
