### ISSUE TITLE
File path problem

### ISSUE THREAD

**Issue by 2661736663** [Arkensor/DayZCommunityOfflineMode#289]
I wanted to save each building separately, and I may revise them later ，Can you tell me where I can find the scene save file

**Comment by 2661736663** [comment]
when I start build a new building, I don't want to load old buildings object，Because of  if I export the new building will contain the old one，

**Comment by Arkensor** [comment]
e.g `C:\Users\Arkensor\Documents\DayZ\COMObjectEditorSave.json`
