### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by MJK52229** [Arkensor/DayZCommunityOfflineMode#294]
Says there´s and undefined function ´LocalValue´, when I looked at it was used to ascertain the Yaw/ Pitch of aiming for the mouse.

float yawDiff = input.LocalValue("UAAimLeft") - input.LocalValue("UAAimRight");
				float pitchDiff = input.LocalValue("UAAimDown") - input.LocalValue("UAAimUp");

Thus I cannot run the game, if anyone is aware how to fix this please do let me know.
![unknown](https://user-images.githubusercontent.com/82844821/115303547-0f465080-a164-11eb-9c12-d4736d99ddc5.png)

**Comment by AssaWolf** [comment]
Same problem

**Comment by Arkensor** [comment]
Make sure that you are using the latest version of the game and the offline mode.
