### ISSUE TITLE
I just can't see buildings...

### ISSUE THREAD

**Issue by BullDem0n** [Arkensor/DayZCommunityOfflineMode#298]
the game load perfectly and i spawn in the middle of no where and there is no buildings and 
![Screenshot_2](https://user-images.githubusercontent.com/88003399/127052571-e1093dd2-aa86-4516-9c1b-03a342dbd550.png)
trees. items are floating in the air, also the roads have grass, other roads are normal, but if i spawn som buildings i cant see them
![Screenshot_4](https://user-images.githubusercontent.com/88003399/127052662-63df9f55-9075-4232-9e7b-29163a9ccdce.png)
![Screenshot_16](https://user-images.githubusercontent.com/88003399/127052695-95fb7a3e-19a2-4b03-9cfa-28cdf8daa074.png)

![Screenshot_3](https://user-images.githubusercontent.com/88003399/127052618-429b5cd6-ea01-4e70-89e4-c3256c74948e.png)

![Screenshot_1](https://user-images.githubusercontent.com/88003399/127052516-90559cdb-5698-4a10-9318-440d468eeaef.png)

**Comment by Arkensor** [comment]
Sorry, I do not think I can help with this. That looks like a game issue to me.
