### ISSUE TITLE
[Issues]Plugin manager

### ISSUE THREAD

**Issue by Vejyl** [Arkensor/DayZCommunityOfflineMode#3]
NULL pointer to instance
Class:      'PluginManager'
Function: 'PluginsInit'
Stack trace:
scripts/4_World/Plugins/PluginManager.c:118
scripts/4_World/Plugins/PluginManager.c:272
scripts/5_Mission/mission/missionBase.c:101
scripts/5_Mission/someMission.c:32

Runtime mode

**Comment by Vejyl** [comment]
Sorry if i do something wrong, I'm newbie github user ![bitmoji](https://render.bitstrips.com/v2/cpanel/437c2df5-4f38-4685-bdd8-1e60d974ce1a-f84b41bc-ca3e-4ef2-b40c-d433a157d870-v1.png?transparent=1&palette=1&width=246)

**Comment by DannyDog** [comment]
PluginSceneManager that it's referring to is NULL as it's not being properly registered. Ignore the error it shouldn't cause issues in-game. (Unless it does?)

**Comment by Vejyl** [comment]
> PluginSceneManager that it's referring to is NULL as it's not being properly registered. Ignore the error it shouldn't cause issues in-game. (Unless it does?)

I dont know. I went into the game moved away from the place of appearance and took off

**Comment by Arkensor** [comment]
I will look into this for the upcoming updates

**Comment by Vejyl** [comment]
> I will look into this for the upcoming updates 
Thank you
