### ISSUE TITLE
Need to restart each time an existing building gets moved

### ISSUE THREAD

**Issue by Datalus848** [Arkensor/DayZCommunityOfflineMode#313]
1) When place objects with the object spawner, if you try to move the object around while inside a building, you may accidentally move the building and not the object. Then you have restart the program to get the building back to its original location. Can you please create a toggle on/off for moving existing map buildings/items?

2) Also, when selecting an object (from the object placer/robot arm window) from the list by clicking it with mouse cursor, moves the object around to the position of the mouse cursor. This is a source of much frustration, and you have to many times delete that object and replace it (if you can figure out which object it was). Disabling this function (moving it around when clicking in list) would be a huge time saver. A scroll bar like on the OB object window may be just the solution.

3) A simple undo/redo button would be a huge help. just add a FIFO collection/array/queue to the stack

**Comment by Datalus848** [comment]
oh great work by the way! Love this

**Comment by Arkensor** [comment]
Hi,

these are all great ideas, but I do not think that I will be able to make this work with the current code base. This would require a major re-vamp and I think you might be better off having a look at this: https://github.com/InclementDab/DayZ-Editor
