### ISSUE TITLE
Large Tent Backpack

### ISSUE THREAD

**Issue by TheBoolinRedneck** [Arkensor/DayZCommunityOfflineMode#316]
in the spawn menu when you scroll to the Large Tent Backpack it crashes the game

**Comment by guiltysyndicate** [comment]
This object needs to be added to the  ```autoptr``` array inside the ```ObjectMenu.c``` to prevent the issue from happening

**Comment by TheBoolinRedneck** [comment]
were do i add it im new to this

**Comment by TheBoolinRedneck** [comment]
thank you
