### ISSUE TITLE
Stuck at splash screen.

### ISSUE THREAD

**Issue by blackwolfmagic** [Arkensor/DayZCommunityOfflineMode#32]
Seems that DayZ won't load past the greenish splash screen. I tried running the .bat file as administrator and it said DayZ63.exe not found.

**Comment by blackwolfmagic** [comment]
I tried deleting Missions folder, renaming Battleye and DayZBE back and verifying game files. Still the same issue.

**Comment by JGreatorex** [comment]
I've got a compile error on init.c in the mission folder causing the splash screen to hang. Believe these are related.
Image: http://prntscr.com/jfb8ky

**Comment by JGreatorex** [comment]
Try this from the trouble shooting section

> Script or compile errors: Remove "init.c" and perform a Steam intengrity check on your game. (DayZ->Properties->Local files->Verify local game cache). Might have to click it twice to get the right tool. (Do not trust the custom "DayZ cleanup tool", make sure you run the actual Steam verifier). Then follow the install instructions again.

**Comment by JGreatorex** [comment]
Yeah same result here.

**Comment by blackwolfmagic** [comment]
I do notice that when I run "Reset Hive and Play.bat" that the screen says "Cannot find DayZ64.exe". Can't seem to pause it before it closes to read it exactly, but i'm fairly sure that's what it says. No idea if this is normal or not.

**Comment by blackwolfmagic** [comment]
It's there. DayZ_x64.exe

**Comment by blackwolfmagic** [comment]
I tried installing the new version, still the same issue. One thing that may somehow make a difference: I have DayZ installed on my SDD under the E:\Steam folder which is separate from my OS HDD installation which is on a hard disk drive.

**Comment by blackwolfmagic** [comment]
Solved the issue by running the game with the launch parameters through steam rather than running the .bat file. Could be because I have DayZ installed on a different HDD?
