### ISSUE TITLE
"Y" Button not opening Side menu or crashing game entirely.

### ISSUE THREAD

**Issue by Sagpanda** [Arkensor/DayZCommunityOfflineMode#328]
Loaded up DayZ 1.18 Experimental on offline mode Chernarus, everything loaded and all the other offline buttons/actions work fine apart from the object side menu which should come up on the right which doesn't work at all or crashes my game. Launched it on Stable 1.17 and works just fine. I have re-installed the Experimental as well and still doesn't work.

**Comment by Sagpanda** [comment]
I have now checked that all drivers updated, used a different keyboard and also swapped the key around with it being U instead of Y from the module folder thing I found, still the same result of the game just shutting down instantly. It could be something to do with 1.18 but I think others have got it to work off the bat.

**Comment by Tazzar** [comment]
im having the same problem

**Comment by ABazing** [comment]
Sadly ran into the same issue, hope someone shares a fix 👍

**Comment by Arkensor** [comment]
Thanks for the reports. This issue is now fixed :)

**Comment by ABazing** [comment]
You're awesome as always <3
