### ISSUE TITLE
Character not saving? 

### ISSUE THREAD

**Issue by MrEmuu** [Arkensor/DayZCommunityOfflineMode#33]
Hi! Didn't know save system was added, been looking at files etc but I noticed while storage_-1 is created 
data folder is empty 

players.db is 12kb, 

noticing no saving whatsoever, despite running around for a bit, is this something on my end? Or am I doing something wrong. I have tried exiting the game though clicking exit and the traditional ALT + F4, relogging I come back to a new character. Thanks in advance!

**Comment by krakenkoin** [comment]
Saving isn't in this build, will be in a future release as it states.

**Comment by MrEmuu** [comment]
You sure? (I made a space because I don't want to tag him multiple times) 

> New Playersave System

 master (#25)
@ n8m4re
n8m4re committed 3 days ago

> fix - quickbar not saved on exit

@ n8m4re
n8m4re committed 2 days ago
 
fix - hands not saved after exit

@ n8m4re
n8m4re committed 2 days ago

**Comment by krakenkoin** [comment]
I believe arkensor is looking it over before adding it to the mission file but unsure. The README says "Future : Adding persitent settings and stats saving" wouldn't character saving fall under that section?

You could always try to merge the code yourself and try to get it working maybe?

**Comment by MrEmuu** [comment]
Go check the code, you'll see code that's suppose to save items. Also persistent settings and stats saving are two entirely different features you are aware right? This would be towards thirst and hunger energy etc. The character save system has said upcoming as _"character save system"_ would be to save the character and loot, as I mentioned once again. "fix - quickbar not saved on exit" would not be a feature in the current build if there isn't a save system. The code is there.

**Comment by krakenkoin** [comment]
Yes I was unaware of the code being up I was waiting for it to be released as a whole but I see the code now and updated my files. Everything is working fine as far as I can tell, character saving, hot bar saving, still messing around with it to see if I have any problems.

**Comment by MrEmuu** [comment]
Weird.. Ill do a reinstall and report back

**Comment by krakenkoin** [comment]
I have a problem when I die I'm the same character but hurt in the same spot, but sometimes it will start me fresh when I die

**Comment by MrEmuu** [comment]
`DayZ\Missions\DayZCommunityOfflineMode.ChernarusPlus\storage_-1\data` 

Do you have files inside there? No matter what I do this folder is blank, checked for readonly etc. 

`\DayZ\Missions\DayZCommunityOfflineMode.ChernarusPlus\modules\CommunityOfflineMode.c`
Only option for saving I could find was;

`	protected bool DISABLE_RESPAWN_ONRESTART = false; // enable(true) / disable(false) - Player Respawn on Restart
	protected bool DISABLE_HIVE = false;	 // enable(true) / disable(false) - Hive`

in which changing things, etc hasn't seemed to change anything.

**Comment by krakenkoin** [comment]
Nope my data folder is empty and I didn't change anything, just copied and pasted code to their respected files and launched through the .bat file

**Comment by MrEmuu** [comment]
I've tried exactly that and had zero results. However I only have 7 files in my modules folder, may you send me screenshot of what yours looks like?

**Comment by krakenkoin** [comment]
My modules folder includes :

CommunityOfflineMode.c
ObjectEditor.c
ObjectManager.c
PlayerCreate.c
PlayerSave.c
PositionManager.c
SaveManager.c
WeatherManager.c
WelcomeManager.c

**Comment by MrEmuu** [comment]
Odd! I do not have 
PlayerCreate.c
PlayerSave.c

Despite being on the latest version. I also don't see them in the github repository either?

**Comment by MrEmuu** [comment]
Ohh, appears I didn't download from the tree branch. Closing this now thank you :)

**Comment by DanFAgo** [comment]
Neither do I. Do I have to create those 2 folders then drag the 2 scripts above in to the folder?

**Comment by MrEmuu** [comment]
> Neither do I. Do I have to create those 2 folders then drag the 2 scripts above in to the folder?

This is a post from 2018, no need to necro threads.
