### ISSUE TITLE
Homepage Download Link Error?

### ISSUE THREAD

**Issue by Joeofcoding** [Arkensor/DayZCommunityOfflineMode#330]
**See the screenshot below, "this" link won't work because it is missing a dot after the letter "v" in "v3.8"**

![Screenshot](https://user-images.githubusercontent.com/40191611/171009239-44d3b693-51b5-480b-a196-49b2ca586cb4.jpg)

This does not work:
https://github.com/Arkensor/DayZCommunityOfflineMode/releases/download/v3.8/DayZ.Community.OfflineMode.zip

This works:
https://github.com/Arkensor/DayZCommunityOfflineMode/releases/download/v.3.8/DayZ.Community.OfflineMode.zip

**Comment by Arkensor** [comment]
Yup, was a typo. Was fixed.
