### ISSUE TITLE
Default offline Dayz

### ISSUE THREAD

**Issue by Kilian-Hinterhoelzl** [Arkensor/DayZCommunityOfflineMode#331]
Hi there. Everything works just fine, but I'd like just the default DayZ experience, just in offline.

So nothing from this section:
https://github.com/Arkensor/DayZCommunityOfflineMode#controls
For example the infinite ammo when you press "R"
And I'd like to spawn with nothing but the default stuff (no gun and stuff)

Is there any way to disable/edit this stuff?
I'm a programmer myself, but I've never worked with C before, so I couldn't exactly find it on my own.

Thanks in advance!

**Comment by JonnyBro** [comment]
You can use this from official wiki of the game: https://community.bistudio.com/wiki/DayZ:Modding_Basics#Testing_the_Mod.
Just don't use the **-mod** parameter.

**Comment by Kilian-Hinterhoelzl** [comment]
Thank you!
