### ISSUE TITLE
No world with name "bat"

### ISSUE THREAD

**Issue by CmBSinka** [Arkensor/DayZCommunityOfflineMode#338]
Did everything according to the instructions.
I get this error.
Checked the mission path several times, it's correct.
Please tell me if I am the only one with this error or many?
![DayZ_x64_EzyDNCBhI3](https://user-images.githubusercontent.com/43815006/175609985-f0211820-2be0-45e5-89b1-9bed9d4ebcb3.png)
UPD:  The problem is only observed when trying to start from the Launcher.

**Comment by FreddyCruge1** [comment]
do you solve this?

**Comment by Arkensor** [comment]
You don't select the batch file as mission start in the launcher. There you would select only the folder it is contained in.
