### ISSUE TITLE
You can not teleport while you are inside the freecam ?

### ISSUE THREAD

**Issue by raxto** [Arkensor/DayZCommunityOfflineMode#34]
Why ? It's very helpfull if you can tranform you with freecam to place where you want ?

[https://i.imgur.com/RxgCQ12l.png](https://i.imgur.com/RxgCQ12l.png)

**Comment by krakenkoin** [comment]
You can if you push the freecam button again, it'll teleport to cursor.

Used to be able to tho with T

**Comment by raxto** [comment]
Yes, now i understand, but why not with T ? :)

**Comment by Arkensor** [comment]
This has to do with the upcoming camera manager, this should avoid breaking things completely. Don't worry you will be able to control your player as you like soon
