### ISSUE TITLE
Unable to load workshop mods

### ISSUE THREAD

**Issue by nthclick** [Arkensor/DayZCommunityOfflineMode#343]
Hello I am unable to load workshop mods.
Ive copied the "!Workshop" folder into my "Missions" folder and added the mods to my batch script however it still wont load. 

here is my script and how ive added the mods

@echo off

taskkill /F /IM DayZ_x64.exe /T

RD /s /q "storage_-1" > nul 2>&1

cd ../../

start DayZ_x64.exe -mission=.\Missions\DayZCommunityOfflineMode.ChernarusPlus -nosplash -noPause -noBenchmark -filePatching -doLogs -scriptDebug=true -mod=!Workshop/@Cold_Chernarus;!Workshop/@DisableFireAttachmentDamage;!Workshop/@Immersive_Placing;!Workshop/Winter_Chernarus 

Ive also tried copy and pasting the addon folders from the !Workshop to the "Mission" root folder and updating the bat accordingly and adding a "/Addons" to link it directly to the addons folder

**Comment by Arkensor** [comment]
Hi, you don't copy the workshop folder etc. Have a look at the namalsk launch batch file, it shows you how to load mods:
https://github.com/Arkensor/DayZCommunityOfflineMode/blob/production/Missions/DayZCommunityOfflineMode.Namalsk/DayZCommunityOfflineMode.bat#L9
