### ISSUE TITLE
Looking to contribute

### ISSUE THREAD

**Issue by Brandon10x15** [Arkensor/DayZCommunityOfflineMode#345]
Not sure if I'm in the right place for this, I have made some and am continuing to make quality of life changes to this tool, specially more geared towards map editing and object saving.
I am looking to share my editions and also see where you are with connecting the newer resources to the tool like the cfggameplay.json and such or if you have any pointers on how to do so myself?

**Comment by Arkensor** [comment]
Sorry but what exactly are you asking here for? If you want to propose an update to COM then please make a PR. If you just want some general modding advise please shoot me a DM on discord or something.

**Comment by Brandon10x15** [comment]
Ok great, I wasn't aware of how the PRs worked until after I posted this lol...
But could also use some advise if you can drop your discord name or add me Brandon10x15#0876
Thanks man

**Comment by Brandon10x15** [comment]
Hey I'm getting ready to drop the PR, if I could get in touch with you on discord beforehand that would be great.
I have a couple features that I could use a little clarity on

**Comment by Arkensor** [comment]
> Hey I'm getting ready to drop the PR, if I could get in touch with you on discord beforehand that would be great. I have a couple features that I could use a little clarity on

Sure thing, `Arkensor#1337`
