### ISSUE TITLE
Autorun and Autowalk

### ISSUE THREAD

**Issue by TkX90** [Arkensor/DayZCommunityOfflineMode#347]
Hi, I'm TkX. I wanted to comment on Autorun and Autowalk. Scriptys incremented in the Offline Mode folder. Due to these scripts I can't test my autorun and autowalk mods which is terrible. Well, I can't test it because the folder already contains an autorun and an autowalk. Taking advantage of this comment, I ask the creators a question. Would it be possible to remove these scripts from the Offline Mode folder? Or would it be possible for me to get these scripts out of the folder myself? If yes, could you help me, how can I remove this autorun and this autowalk?

**Comment by Arkensor** [comment]
Hello @TkX90,
yes, you can just go into the missions folder and comment this line out:
https://github.com/Arkensor/DayZCommunityOfflineMode/blob/production/Missions/DayZCommunityOfflineMode.ChernarusPlus/core/modules/ComKeybinds/COMKeyBinds.c#L38

Or simply use a different key than X to toggle autorun.
