### ISSUE TITLE
Cant Compile Error

### ISSUE THREAD

**Issue by G-PK** [Arkensor/DayZCommunityOfflineMode#353]
![DayZ Error](https://user-images.githubusercontent.com/115162778/194322861-1b96e403-b795-4c89-bf2e-c2e0ad598092.PNG)
Unfortunately i get this error message every time I try and launch the game. Any solutions?

**Comment by Arkensor** [comment]
Hey, you installed the mission incorrectly. Extract the `DayZCommunityOfflineMode.ChernarusPlus` into the missions folder as per instructions in the readme.
