### ISSUE TITLE
Using mods from the Steam Workshop

### ISSUE THREAD

**Issue by Sonatine1** [Arkensor/DayZCommunityOfflineMode#355]
Hi!

Can I download stuff like "CF" or other mods like "Building Fortifications" from Steam and will it work with the Offline Mod?

*Edit: And is there any possibility to save offline? I was testing something for base building and needed to go and when I went back to the game everything was fresh. An option to save would be pretty helpful...

Best regards
Sona

**Comment by Arkensor** [comment]
Yes, you can use mods, just adjust the batch file to include "-mod=!Workshop\@Moddname".

No there is no persistence for that. Only manually placed objects are saved from the object spawner.
