### ISSUE TITLE
PersistencyModule complier error

### ISSUE THREAD

**Issue by PSHacks** [Arkensor/DayZCommunityOfflineMode#357]
Hi! First of all - thanks for this mod! Question is - Persistense is commented in ModuleManager.c, so there no save option. If uncomment - errors (guessing - gui stuff?) So, will it be fixed sometime or its impossible? Thanks!

**Comment by Arkensor** [comment]
Hey, that module was never fully implemented and likely won't be either. Its code will be removed at some point. If you need persistent play sessions you need to run a local server.
