### ISSUE TITLE
Items other than using Spawn

### ISSUE THREAD

**Issue by aDioS786** [Arkensor/DayZCommunityOfflineMode#358]
Hi
When an item(s) been spawned using function other than G > Spawnscript for few cars, all other items doesn't show up in ReClass/Memory. Not sure how can we load these in same list as of where other items gets loaded? Thanks

**Comment by Arkensor** [comment]
Not sure what you mean, the item spawning to have them in the object editor list only works when you use the object spawner. If you spawn anything by other means they are not included.

**Comment by aDioS786** [comment]
Thanks for getting back. I am analysing memory and learning. So all items which are spawned by default, are in list 0x8 from each other. So I can see all the items in them. When I go OB > and spawn items on ground / cursor. They do not get added to that list. If I go to Script Function > and execute the 5 scripts in there e.g. Spawn Sedan, Gunter 2 etc, they straight way can be seen in the list getting added. So this is what I was asking, that what is the reason and how can I spawn these in a way that they do get added into same Entity List. And I am testing all these by spawning them like 10m away from me.

**Comment by aDioS786** [comment]
Hi Arkensor
I've had another look and I was doing a silly mistake. It is all working as expected and can see them loading fine. Many Thanks this mode is really helpful.

Thanks
