### ISSUE TITLE
i cant save my game

### ISSUE THREAD

**Issue by lShadowWl** [Arkensor/DayZCommunityOfflineMode#360]
i cant save my game ... every time i launch the game i have to start from the same beginning (RIP loot)  .... is there a solution ??

**Comment by reboarn** [comment]
same please i spend 2 hour and get crashed, and play again start from beginning, please someone tell solution

**Comment by ArturBlazejczyk** [comment]
same problem

**Comment by Arkensor** [comment]
offline mode is only for sandbox testing, loot, etc is not persistent.

**Comment by Chad90b** [comment]
> and player who do want to experiment around **but not loose all their progress** from online.

**Comment by Parker0712477** [comment]
So does offline mode mean there is no save function?

**Comment by philmriss78** [comment]
Why not use a DayZ server, set up a local server and have all the advantages of persistence?
