### ISSUE TITLE
"Compile Error"?

### ISSUE THREAD

**Issue by CryptedPhone** [Arkensor/DayZCommunityOfflineMode#361]
![Error](https://user-images.githubusercontent.com/78257090/215252903-981eeb2e-12d9-4bae-87cf-620ded5790a1.png)

I followed all the instructions thoroughly and also verified my game files and reinstalled to no avail. Any help?

**Comment by Arkensor** [comment]
Does that sound like it is using outdated code maybe? The error message does not fit the current source code at all. Download a fresh copy and make sure you are starting that and not any old copy you had laying around

**Comment by calixo9** [comment]
having the same issue
