### ISSUE TITLE
Not really a bug 

### ISSUE THREAD

**Issue by HubZ5** [Arkensor/DayZCommunityOfflineMode#366]
Hello from 2023. I just downloaded offline mode 4/15/23 and was wondering how I can set up my characters gear so I always have the same items upon start-up.  I get the occasional crash and my games won't save but I'm also running this on an HP Omen.  Settings set to extreme and it runs rather well.  I would just like to be able to load in with something other that the usg45.  I know how to spawn on items but it just takes so and it's so tedious.  Thanks in advance.

**Comment by HubZ5** [comment]
It is now 4/16/23.  I've been messing around on this awesome mod for about 6 hrs.  Super fun.  Super cool.

**Comment by PaperCivit** [comment]
Just edit the StaticFunctions.c file in your missions folder path ie: C:\SteamLibrary\steamapps\common\DayZ\Missions\DayZCommunityOfflineMode.ChernarusPlus\core\StaticFunctions.c

**Comment by HubZ5** [comment]
Awesome, more is there an easier way to find the lat lady of items other than going through the lust that opens the browser.  You don't happen to have a YouTube video on this, do you?

**Comment by HubZ5** [comment]
Never mind, I found a convenient link on GitHub.  But what file would I go under to change the loot density.  I'm going for a very scarce and difficult survival scenario, I have no internet right now.  Also what file would be to adjust the day/night hours and is and is there a certain ratio and minute combo.  For example I think right now it's at 11/1 with like 70 something minutes for day.  I did a lot of clicking when I saw that and I can't remember what file it was I audio don't went to change the wrong one.  Thanks in advance.  I did however successfully change my spawn location and character gear.

**Comment by Arkensor** [comment]
Loot spawn is controlled by the xml files. There is nothing in COM specifically about this. You will need to learn about the loot system in vanilla and see how you can modify the xmls through official and community tools to create the result you desire.
