### ISSUE TITLE
Cant use any character movements while in free cam

### ISSUE THREAD

**Issue by ghost** [Arkensor/DayZCommunityOfflineMode#369]
All i can do in free cam is check inventory and use action features as in eat food and fly around with the usual camera options. When it comes to any character movement tho the keys are not working and i cant raise weapon or shoot either. I have asked a few other people who use it and its not an issue for them. Iv tried resetting my keys, taking of other mods and going vanilla with just community offline and iv tried pressing everything to see if its somehow been set to something else. Also in my controls settings its not actually an option to use free cam character movements or any key settings. Am i missing something really obvious?

**Comment by Arkensor** [comment]
Yes, you not being able to move while in free cam is intentional. It is meant for flying around and teleporting, and or taking screenshots of your character. So for that, you want to not accidentally move while in it.

Inventory and food etc working is a side product of me forgetting to disable that too.

**Comment by ghost** [comment]
Ahh right okay fair enough.. im still confused tho as you have the controls on the read me page as 

X - Toggle Autojog/walk/run
X + SHIFT - Enable Autorun (Just X to disable it again)
X + CTRL - Enable Autowalk (Just X to disable it again)

So this is no longer a feature?

Thanks for the fast response!

**Comment by Arkensor** [comment]
These are for while you are not in freecam.
