### ISSUE TITLE
Control CameraFOV numerically.

### ISSUE THREAD

**Issue by raxto** [Arkensor/DayZCommunityOfflineMode#37]
Give us options:

1. to control CameraFOV by numbers
2. display actual CameraFOV (for example in debug monitor)

btw. what is minimal and maximal available CameraFOV ?

**Comment by DannyDog** [comment]
We'll get to something like this soon. The minimal fov allowed is 0.01 and there is no maximum however very high values can end up breaking your game so try to avoid that xd

**Comment by raxto** [comment]
omg same like Arma, again it's not possible to make fov 0

**Comment by DannyDog** [comment]
Yes of course you can't make it 0 because then you won't have ANY fov and it'll break.

**Comment by raxto** [comment]
any news with Camera FOV control ?

**Comment by S4MT3K** [comment]
If iam not 100% stupid today, the new camera interface has a fov modulater. By pressing z the menu opens to your right. There is a little camera and in ther are a bunch of modulators. 

All statements without guarantee
🤗

**Comment by raxto** [comment]
in ver 2.3 i can't see any FOV control.
