### ISSUE TITLE
1.22 Item spawn Qty 0

### ISSUE THREAD

**Issue by GuizRTQC** [Arkensor/DayZCommunityOfflineMode#373]
When i try to spawn item with the admin menu i spawn all the item with Qty 0

**Comment by BaND1t-v-N0SKe** [comment]
Same problem

**Comment by Jixury** [comment]
Same, I need to make videos for my TikTok and I can't work enymore. It needs to be fixed quickly PLZZZ ! 🙏

**Comment by Arkensor** [comment]
In the spawn menu there is a quantity input where you can enter a different value. I will check why it defaults to 0 in the mean time

**Comment by Arkensor** [comment]
Fixed in: https://github.com/Arkensor/DayZCommunityOfflineMode/releases/tag/v4.1

**Comment by Jixury** [comment]
Thank you very mutch 🙏❤️
