### ISSUE TITLE
I know we're a long ways out but..

### ISSUE THREAD

**Issue by krakenkoin** [Arkensor/DayZCommunityOfflineMode#38]
Is it possible we'll see A.I. bots like a Sarge AI system on this offline mode?

Or would it make sense to wait till a further branch with more final code to even bother starting?

Just wondering of the possibilities, thanks to everyone contributing to this!

**Comment by Arkensor** [comment]
Hello,

we already looked into AI, and right now we haven't managed to get AI as in AI players that hunt you down etc working. However as soon as its possible / we found out how its possible right now we will add something in that regard

**Comment by raxto** [comment]
https://www.youtube.com/watch?v=aavPbobAMp4

**Comment by krakenkoin** [comment]
Thanks for that @Arkensor

@raxto I did some minor stuff with DayZ mod with custom LAN missions for my friends with rMod, Sarge A.I. and Wicked A.I as well all together. 

I'm not much of a coder but I don't mind getting my hands dirty to learn something.

**Comment by MrEmuu** [comment]
Id love this! I've been waiting for so long just to have AI again on DayZ Standalone
