### ISSUE TITLE
how to add mods and bots to spawn ?

### ISSUE THREAD

**Issue by AdrianDrak** [Arkensor/DayZCommunityOfflineMode#383]
not zombies or animals, just humans, everytime i attack them with a club it doesnt knock them out just kills them when i use open editor

anyway to not kill npcs that are human and add human bots and other mods ?

also looks like you don't have humans to spawn

**Comment by Arkensor** [comment]
No as the game has no human NPCs in vanilla. If you have any custom mods to load up just add them to the startup parameters
