### ISSUE TITLE
Change character? 

### ISSUE THREAD

**Issue by MrEmuu** [Arkensor/DayZCommunityOfflineMode#41]
Hello! I want to change the CreateRandomPlayer value in playercreate.c so I can spawn as the survivor I would like and just that one, how would I go about doing this? Thank you very much in advance :)

**Comment by krakenkoin** [comment]
I thought I had a file with every survivor name but can't seem to locate it. Tried to peek at the files but dinner was ready, I'll keep looking later tonight as I'm interested in this as well.

**Comment by MrEmuu** [comment]
You can find the survivor names easily in the editor. Just type M or F and they'll show up

**Comment by krakenkoin** [comment]
Yaya but I was gonna see the code structure on that bit to see how it chooses players so I could change the player spawn from random to just the blonde female haha

**Comment by krakenkoin** [comment]
Not sure where to put it but I think this is it

string preferredCharacter = "CharacterNameHere";

**Comment by wriley** [comment]
@krakenkoin Here's the character names if you still need a handy list

/*  === Characters ===
    SurvivorM_Mirek
    SurvivorM_Boris
    SurvivorM_Cyril
    SurvivorM_Denis
    SurvivorM_Elias
    SurvivorM_Francis
    SurvivorM_Guo
    SurvivorM_Hassan
    SurvivorM_Indar
    SurvivorM_Jose
    SurvivorM_Kaito
    SurvivorM_Lewis
    SurvivorM_Manua
    SurvivorM_Niki
    SurvivorM_Oliver
    SurvivorM_Peter
    SurvivorM_Quinn
    SurvivorM_Rolf
    SurvivorM_Seth
    SurvivorM_Taiki
    SurvivorF_Eva
    SurvivorF_Frida
    SurvivorF_Gabi
    SurvivorF_Helga
    SurvivorF_Irena
    SurvivorF_Keiko
    SurvivorF_Linda
    SurvivorF_Maria
    SurvivorF_Naomi
*/
