### ISSUE TITLE
Found something interesting..

### ISSUE THREAD

**Issue by krakenkoin** [Arkensor/DayZCommunityOfflineMode#42]
If you hold (S+RMB) you can throw punches (LMB) at zombies all day without taking any damage, just thought I'd share ;)

(Edit : also works with melee weapons - I'm guessing it's bugged this way cause blocking isn't implemented yet?)

(Edit#2 : well it doesn't work on wolves lol.. got sniffed out by 6 of them shot 2 and the others ran off.. needless to say I now have some wolf steaks for the camp!)

**Comment by blackwolfmagic** [comment]
Blocking IS implemented. You hold RMB + S to block. This sounds like a bug where you can strike while blocking.
