### ISSUE TITLE
Possible error with object editor?

### ISSUE THREAD

**Issue by DoctorDeSync** [Arkensor/DayZCommunityOfflineMode#43]
Every time I enable the object editor it only allows me to select objects, but I can't manipulate them in anyway (even objects I spawn in). 

Is it possible the error occurs when I enable the object editor, but it also enables god mode at the same time?

**Comment by DannyDog** [comment]
The error shouldn't be the result of god mode being enabled at the same time. The version i gave you is still wip and all the keybinds haven't been moved to the new system yet. So you cannot drag objects even after selecting them then clicking and dragging?

**Comment by DoctorDeSync** [comment]
Yes. I also cannot roll, pitch, yaw or move objects up/down either.

**Comment by lonewolfss** [comment]
i have sort of the same problem my items go sky high when trying to move them

**Comment by lonewolfss** [comment]
> 
> 
> That has been fixed in the development branch.

im using that now but how do i save my placed items i have tryed to press ctrl and s but it only copys the item name

**Comment by DannyDog** [comment]
I have not yet pushed it to the branch yet. It will come soon

**Comment by lonewolfss** [comment]
> 
> 
> I have not yet pushed it to the branch yet. It will come soon

ahhh noooooo lol just  being working on a bridge for over 2 hours :(  away for me to save this

**Comment by lonewolfss** [comment]
> 
> 
> I have not yet pushed it to the branch yet. It will come soon

any eta on the update so i can rebuild my bridge lol and save it to my private server if you dont want to publicy change could you please forward it to me thanks

**Comment by S4MT3K** [comment]
I hope you guys can help me? How can i extract the info of placed buildings? I have another mod on the Server and can spawn Buildings. But i need the info, and the modder (DaOne) says it is possible to extract the position of a building (yaw, roll, heigh, x,y,z and so on) Hope you guys can help me. Thx
