### ISSUE TITLE
Spawning Player Models and Zombies 

### ISSUE THREAD

**Issue by DoctorDeSync** [Arkensor/DayZCommunityOfflineMode#44]
Whenever I spawn a player model (normal or decayed) or zombies and I kill them, the game seems to think my character has died but doesn't do anything unless I restart the mission file or close out of the game.

Method of spawning is through the item/object spawner

**Comment by Lijazos** [comment]
Looks like the new Stress Test patch released today fixed this.

**Comment by krakenkoin** [comment]
So I can update and it won't effect these mission files with errors?

**Comment by DannyDog** [comment]
I did find a few issues with the recent update so i'll have to check that. But it should work ok.

**Comment by krakenkoin** [comment]
I've been scared it'll break the offline game completely so been avoiding it lol

**Comment by DannyDog** [comment]
Nah it shouldn't lol.
