### ISSUE TITLE
Can't compile "World" script module!

### ISSUE THREAD

**Issue by desyncing** [Arkensor/DayZCommunityOfflineMode#49]
Can't compile "World" script module!

scripts/4_World/entities\core\inherited\dayzinfected.c(29): Multiple declaration of class 'DayZInfectedCommandAttack'

Runtime mode
CLI params: mission .\Missions\DayZCommunityOfflineMode.ChernarusPlus nosplash  noPause  noBenchmark  scriptDebug true

**Someone help?**

**Comment by MarkAndrew1234** [comment]
same problem for me ...

**Comment by DannyDog** [comment]
Are you updated to the latest stress test version? Also make sure you remove any modified script folders or pbo and re verify your files if you downloaded previous versions before the version with the Mission file.

**Comment by cg5081** [comment]
I still get this error and cannot find a work around

**Comment by Jacob-Mango** [comment]
Are you on the Stress Test branch?

Do a steam verify integretity check.

Can you join normal servers?

Make sure you are downloading from the releases section.

Delete the folder "scripts" found in the root directory of DayZ installation if it exists.

**Comment by gman0428** [comment]
@Jacob-Mango if you see this how do you get root directory to do that?
