### ISSUE TITLE
Free camera problem.

### ISSUE THREAD

**Issue by SekySVK** [Arkensor/DayZCommunityOfflineMode#54]
Hi,

I have problem with free camera. When I press **INSERT** game open inventory, change camera to 1st/3rd person and write my position and sometimes spawn zombie or sometimes game starts teleporting my character around all map, but I have not got free camera. 
What is the problem?

And in the end I really like your community offline mode, for me is better than original offline mode from devs and sorry for my English I am from SLOVAKIA.

Thank you!

**Comment by DannyDog** [comment]
T is the key to teleport. INSERT is to turn on free camera and turning it off teleports you to the position you're looking at. I suggest changing open inventory to a different key for now to avoid this issue.
