### ISSUE TITLE
errors when launching

### ISSUE THREAD

**Issue by fatboi615** [Arkensor/DayZCommunityOfflineMode#6]
https://gyazo.com/15b7b6c9ed068ae0480c2f9a1d7981de

**Comment by rwckr** [comment]
@fatboi615 - Did you make any progress on this? I'm currently experiencing the same issue.

**Comment by rwckr** [comment]
@fatboi615 
→ right click DayZ in your Steam Library
→ click Properties
→ click the Betas tab
→ go all the way down to Enter beta access code to unlock private betas"
→ enter ireallywanttotest
→ the "Stress Test Branch" is unlocked - select that branch in a drop down menu and let the client files download

Then follow installation instructions.

**Comment by Arkensor** [comment]
@rwckr That you for that explanation. I will add it to the readme for those who missed the "be on the stress test part" :)

**Comment by fatboi615** [comment]
now i get this https://gyazo.com/e9c248db918f3936afb5eb27e165cc77

**Comment by Arkensor** [comment]
Yes I need to update the mod. Give me a moment

**Comment by fatboi615** [comment]
ok thanks
