### ISSUE TITLE
How to Script in DayZ SA

### ISSUE THREAD

**Issue by The-Scifer** [Arkensor/DayZCommunityOfflineMode#60]
Hi,

I just found this project and started customizing my player spawn profile, which is going very well so far. Someone please help me to understand this new C scripting cause Google wont help me.

How did you guys learned this new scripting **in detail**?

**Comment by n8m4re** [comment]
1. you need a basic knowlegde in programming  ( Object Oriented Programming )
2. research & analyse the game scripts ( unpack:  /dta/scripts.pbo )
3. try & error
4. have fun

**Comment by The-Scifer** [comment]
@n8m4re Thank you!

What is the best tool for managing/unpacking pbo files nowadays?

**Comment by n8m4re** [comment]
may not the best, but it does the job:  http://www.armaholic.com/page.php?id=16369
