### ISSUE TITLE
Cannot compile mission script! 

### ISSUE THREAD

**Issue by moliorrs** [Arkensor/DayZCommunityOfflineMode#62]
Using the newest test branch

Yes, I have re-downloaded Dayz, validated steam files, and re-downloaded the newest mission. 

![b9f31f01628816bda76a0f24b949af94](https://user-images.githubusercontent.com/31002931/43532810-5f5b710a-9581-11e8-84f7-d97c71882b91.png)

**Comment by Arkensor** [comment]
This was resolved with the latest patch
