### ISSUE TITLE
New Mission Change Character?

### ISSUE THREAD

**Issue by Jaw1985** [Arkensor/DayZCommunityOfflineMode#63]
Is there a way of changing the default character? Previously, you could amend Playercreate.c to achieve this, but can you do this now?

**Comment by Arkensor** [comment]
Hello,

yes you can change the default character by editing this file: https://github.com/Arkensor/DayZCommunityOfflineMode/blob/master/Missions/DayZCommunityOfflineMode.ChernarusPlus/modules/CommunityOfflineMode.c#L1027

**Comment by Jaw1985** [comment]
Thank's for the response, wherein the code would I change it to add say - SurvivorM_Jose? the "None" part?

m_oPlayer = PlayerBase.Cast( GetGame().CreatePlayer( NULL, GetGame().CreateRandomPlayer(), positions.GetRandomElement(), 0, "NONE") );

**Comment by Arkensor** [comment]
No instead of GetGame().CreateRandomPlayer() put int "SurvivorM_Jose"

**Comment by Jaw1985** [comment]
Sorry, could you give me an example of where to put it exactly in that line? I keep breaking it.

**Comment by Arkensor** [comment]
m_oPlayer = PlayerBase.Cast( GetGame().CreatePlayer( NULL, "SurvivorM_Jose", positions.GetRandomElement(), 0, "NONE") );
