### ISSUE TITLE
Unable to save?

### ISSUE THREAD

**Issue by bananaholster** [Arkensor/DayZCommunityOfflineMode#74]
Is there a branch released where I can save, spawn undead, and edit objects?
I got the most recent development branch but I seem unable to use many of the old commands have they been removed to be later added to the new GUI?

**Comment by DannyDog** [comment]
Yea sorry. The development branch is still being developed on. Were currently porting a lot of stuff to a new system as well as persistency but its not 100% complete yet. I recommend to download the release version instead.
