### ISSUE TITLE
DayZ SA scripting

### ISSUE THREAD

**Issue by AgentLV** [Arkensor/DayZCommunityOfflineMode#77]
Hello,
I'm new to DayZ scripting and I was wondering if there is a way to setup this project in an IDE and use auto completion and other treats or do I have to write everything "manually" and also search for methods, variables, etc. in the dta/scripts.pbo?

All kinds of help and information is welcome :)

**Comment by DannyDog** [comment]
Afaik the new workbench tool will come with auto completion and proper documentation viewing. Hopefully :/
