### ISSUE TITLE
items and building dont save

### ISSUE THREAD

**Issue by lonewolfss** [Arkensor/DayZCommunityOfflineMode#79]
hello im trying to add items in to the map so i can transfer them to my server but they dont save

if i have to save how do i do this and where do i find the file with all the info in to copy to my server atm i can only spawn 1 item in on my server and its using this command 
vector spawnPos = "5101.49 27.48462 2420.01";
GetGame().CreateObject( "Land_Construction_Crane", spawnPos, false );

**Comment by DannyDog** [comment]
I wrote a script for this. I will push a build for this.

**Comment by lonewolfss** [comment]
> 
> 
> I wrote a script for this. I will push a build for this.

ahhh nice so is this a easy method to do then as just add in game with offline mode then save and then copy the code into the sever side ?

**Comment by DannyDog** [comment]
Added. Please redownload. https://github.com/Arkensor/DayZCommunityOfflineMode/archive/development.zip
