### ISSUE TITLE
Item Snapping/Help

### ISSUE THREAD

**Issue by lonewolfss** [Arkensor/DayZCommunityOfflineMode#80]
hi guys im trying to place items down but i need a way to snap some togther    ive found a dam im using as a bridge but when i place the second one it will go sky high is there a fix on this ?

**Comment by DannyDog** [comment]
Snap together like snapping walls together? I'm not sure that's possible sorry.

**Comment by S4MT3K** [comment]
With the devoloping version it is almost possible to snap things togeter... just place the item nearly where it has to be. Type the heigh manually in and place the item via Mousescroll (hover over x,y and for precision heigh over z too) perfectly.

If you want a video i can make one, but i hope you understand what i mean. 
It is also possible to Save the places buildings and extract them later. The only thing i Don’t get working is playersave and the godmode laserpointer thing (game crashes when i try to execute)


Regards S4MT3K

**Comment by DannyDog** [comment]
Thats not snapping that's manually inputting the positions...As for your crashing what game version are you on and are you using the latest com version?

**Comment by S4MT3K** [comment]
I am on the actual StressTest from steam and using your latest development branch.

**Comment by DannyDog** [comment]
The execute is for the functions on the left. I'll fix that crash.
