### ISSUE TITLE
object exports not producing correct code? (current dev branch)

### ISSUE THREAD

**Issue by robbhimself** [Arkensor/DayZCommunityOfflineMode#82]
[Just placed one building to test the export code using ctrl +s ](https://i.imgur.com/48u53a0.jpg)

[This is the code copied to clipboard](https://i.imgur.com/alRc364.png)

its not exporting any coordinates or anything just the classname. am i doing something wrong? 

also is there a way to save a project to continue later?

**Comment by robbhimself** [comment]
> Sorry i may have jumped the gun there. It's not currently in the dev branch yet. I'll push it in soon.

thanks. also j/w if there will be a way to save progress on edits to continue later? or a way to re-import them?

thanks

**Comment by DannyDog** [comment]
Added. Please redownload. https://github.com/Arkensor/DayZCommunityOfflineMode/archive/master.zip
