### ISSUE TITLE
Compile error with 0.63149137 (Stress Test #51)

### ISSUE THREAD

**Issue by Asmond** [Arkensor/DayZCommunityOfflineMode#83]
Just a heads up guys.

- **Issue:** Im getting a compile error with the last two builds of the Stress Test (#50 and #51). 
- **Details:** Can´t compile mission init script! $CurrentDir://missions//DayZCommunityOfflineMode.ChernarusPlus//modules//SaveManager.c(353): Undefined function "GetStatTemperature".
- **Screenshot:** https://i.imgur.com/5MuA6ja.png

**_Thanks!_**

**Comment by DannyDog** [comment]
Are you running latest dev branch? Please re-download incase you haven't.

**Comment by JonnyBDev** [comment]
Hi. Downloaded the latest stress-test like a hour ago.
Got the same compile error with "GetStatTemperature".

**Comment by rikardu92** [comment]
Hi. Im having the same problem. cant load it.

**Comment by Asmond** [comment]
21/10: Worked with this one: https://github.com/Arkensor/DayZCommunityOfflineMode/tree/development
No problems at all in the last stress test branch and the new UI is fantastic. 
Great work guys!

**Comment by DannyDog** [comment]
👍
