### ISSUE TITLE
Please revert back to original camera controls/keybinds

### ISSUE THREAD

**Issue by DoctorDeSync** [Arkensor/DayZCommunityOfflineMode#84]
I can understand having a menu to provide specific numerical inputs, but these new controls make little sense to the previous version. Instead of right clicking and dragging up or down with my mouse I have to go an place the exact number I want. I found it much easier using the old controls then I do with these new ones, and having to resort to inputting numbers when I already knew the controls makes it take longer to do things I want.

**Comment by DannyDog** [comment]
What in particular? The controls are pretty much on par with the old version except fly speed and fov. Fov is just scroll wheel and fly speed is shift modifier.

**Comment by DannyDog** [comment]
Gotcha. I know exactly what i can do to make it even better than that.

**Comment by lonewolfss** [comment]
> 
> 
> Gotcha. I know exactly what i can do to make it even better than that.

DannyDog when will the ctrl+s be working again i really need this :D thanks

**Comment by DannyDog** [comment]
Today. Ill push an update for it today along with the camera stuff. Keep an eye on it :)

**Comment by DannyDog** [comment]
Ok pushed. Please redownload as well as give me feedback on camera controls. I've changed them back what it was before.

**Comment by DoctorDeSync** [comment]
I like what you did but is there a way to remove that smoothing or "catch-up" the camera does when it tries to match the fov change?

**Comment by DoctorDeSync** [comment]
Nice! My only problems with it is the "catch-up" effect it seems to have when the camera is trying to match the fov. Another thing is not being able to freeze the camera in place unless I open up the menu. Was the keybind changed for that or was it removed?

**Comment by DannyDog** [comment]
The catchup effect is literally fov smoothing. I thought youd like that since itll be handy making cinematics with it. All the videos ive seen of cinematics using the old tool had that terrible mouse jankiness. I believe the keybind should work. [Backslash]

**Comment by DannyDog** [comment]
But i will add an option to disable it then.

**Comment by DannyDog** [comment]
Option added in commit https://github.com/Arkensor/DayZCommunityOfflineMode/commit/e80a7300da07db7e0144108d17d50ca7cb3cd97f
