### ISSUE TITLE
Compile Error 

### ISSUE THREAD

**Issue by Sgttater** [Arkensor/DayZCommunityOfflineMode#86]
http://prntscr.com/l8rgor

I've had this problem all day. Yes, I've done everything from uninstalling to deleting po or whatever and script folder.

I even reinstalled dayz from normal to stress test in order.

**Comment by S4MT3K** [comment]
> 
> 
> stress test ??? its expermental correct me if im wrong

You can use the mod with both, Exp or stresstest. (Works for me)

@Sgttater  Did you copied the mod to the missionfolder? i had it first wrong and only started it without putting it into the missionfolder of an existing copy of dayZ ^^ I dont even know why tbh^^

**Comment by Ilya70007** [comment]
Same here, doesn't worn either on stresstest or experimental

**Comment by S4MT3K** [comment]
you guys tried to use the Development Branch from arkensors mod?

**Comment by Ilya70007** [comment]
> you guys tried to use the Development Branch from arkensors mod?

I didn't see it there, will try it out now

**Comment by Sgttater** [comment]
how the hell do you launch offline mode using dev branch?

**Comment by Sgttater** [comment]
And how do I find it from this page? I can never find it, i hate github

**Comment by SlounyCZ** [comment]
Same problem

**Comment by S4MT3K** [comment]
When youre on the mainpage, click on branch ;)
