### ISSUE TITLE
[QUESTION] Placeable Objects

### ISSUE THREAD

**Issue by S4MT3K** [Arkensor/DayZCommunityOfflineMode#87]
Hey you :D

Short question and/or suggestion:
I figured out that some Objects are missing. i tryied to build a tenttown at the krasnostav Airstrip and couldnt find the Sandfilled buildingblocks or normal Sandbags. Is it just impossible or did i something wrong? I also couldnt find Roads, curbs trees etc. I also wonder if it is possible to erase some thing out of the map and save it. But the most important thing is the missing Military Basebuild parts. Regards S4MT3K

**Comment by DannyDog** [comment]
Those map objects cannot be spawned as they do not have any class definitions for them in the vanilla game. All the objects you see that can be spawned have them and are visible in the object spawner. Sucks :/

**Comment by DannyDog** [comment]
It would require a client side mod yes.

**Comment by S4MT3K** [comment]
Can you please <3 tell me where i can find the entries that i can start hardcode them? (i mean the unplaceable objects like pathes,tankwrecks,tables,milit.barbwire etc,) Thank you :D
Ill write classdefinitions and try to implement them over a plugin or just into addons. IDK :D But first of all i need the names :D hop you can help me :D

**Comment by DannyDog** [comment]
Quick update. Sorry it's not possible to grab model name from the object since theres no class for it. You may need to go ahead and manually look in the game files to find out the names. Sorry.

**Comment by S4MT3K** [comment]
Perfect. Thank you :-*

**Comment by S4MT3K** [comment]
UPDATE: I am writing the classes right now Manually. I know theyre apparently erased with the next update but if you need them let me know. if you dont update your DayZ or reinstall theyre might be useful! PS: Is there a way to implement modded clientfiles via the server without modding the server at all? That we say that the client has to use this files on the server instead of his own?

Greetz S4MT3K

**Comment by lonewolfss** [comment]
dose anyone know why Land_Dam_Concrete_20_Floodgate dose not spawn now has it had a name change

**Comment by S4MT3K** [comment]
> 
> 
> dose anyone know why Land_Dam_Concrete_20_Floodgate dose not spawn now has it had a name change

Nope is still the same name
