### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by tobiasReichel** [Arkensor/DayZCommunityOfflineMode#9]
![dayzsp](https://user-images.githubusercontent.com/13315271/39392234-b95c8ef6-4ab2-11e8-8d9e-4d744c5f52a6.PNG)

i installd the newest version and this happend

what can i do?

**Comment by RyobiTobi** [comment]
Same here, I followed the installing instructions but just got that error message. A fix would made my day tho :)

**Comment by Arkensor** [comment]
Hello @tobiasReichel and @RyobiTobi,

have you tried downloading the latest version 1.1? https://github.com/Arkensor/DayZCommunityOfflineMode/releases/download/v1.1/DayZ.Community.OfflineMode.zip

**Comment by RyobiTobi** [comment]
For some reason, I reinstalled the whole thing and it worked. Strange. But I have another question: Is it possible to spawn items, such as AK's or Clothes, with the developer admin tool? I can't figure out how at the moment. Thank you :)

**Comment by Arkensor** [comment]
Yes: 
DELETE - Open the DayZ developer admin tool

Then on the bottom left you can search for AK, and all items that are related to that should appear. Then click the ARM for example and choose presets. then you see the button to spawn on ground, spawn in inventory etc

**Comment by tobiasReichel** [comment]
okay now it works
strange thing


thanks for the quick reply

and good job on the hacky Mod
