### ISSUE TITLE
DayZ crashing at launch

### ISSUE THREAD

**Issue by supersharky** [Arkensor/DayZCommunityOfflineMode#95]
Here's a log file

Log C:\Users\Marius\AppData\Local\DayZ\script.log started at 20.11. 17:39:03

SCRIPT       : Registered 361 temporary action enum(s), UAN==361
SCRIPT    (W): @"scripts/3_Game/dayzplayer.c,348": Missing ';' at the end of line
SCRIPT       : CreateGame()
SCRIPT       : Loading Inc: 1

**Comment by Arkensor** [comment]
Try out the latest version of COM, and if that does not fix the issue try validating your files maybe.
