### ISSUE TITLE
items not saving

### ISSUE THREAD

**Issue by lonewolfss** [Arkensor/DayZCommunityOfflineMode#98]
hi so keeping it short added stuff to map saved checked jason file says its saved but loading back into game to edit items and move placment and items dont load in is there a fix for this please

**Comment by lonewolfss** [comment]
any reason to why this is  not saving i have even tryed to add them in to the file manual but it still wont load them in ?

**Comment by S4MT3K** [comment]
For some reason, the New DayZ version and The newest development branch from Arkensor is erasing my folder. Maybe this is the Problem? Or is everything in the file bit its not read out?

**Comment by Arkensor** [comment]
Hey, can you check how your start you game please, cause there was a new parameter introduced that reenabled file write operations and with that the object saving. Just use the latest release and use the batch file there to launch COM

**Comment by S4MT3K** [comment]
Just to be safe, master or development branch?!?

**Comment by lonewolfss** [comment]
ahh ok this is the dev mode i start via the bat file

**Comment by DannyDog** [comment]
Does this bug still occur? @lonewolfss. Please try again with latest development branch.
